### PR TITLE
Update dependence

### PR DESCRIPTION
**Pull request by lyj0309**
Signed-off-by: lyj <2457395722@qq.com>

### CODE REVIEW

**Comment by Jamstah** [comment]
FYI: If you update your main branch in your repo, this PR will automatically reflect the changes. You don't need to close the PR and open a new one every time :)

**Comment by Jamstah** [comment]
Can you say why you are updating these dependencies?

Is it just because they are old? Is there a security vulnerability you are fixing? Is there a bug that is affecting you?

**Comment by milosgajdos** [comment]
> Can you say why you are updating these dependencies?

This is a valid question, but I'm looking at the diff and can see they're finally properly tagged which is great for readability. But I agree we don't need to go ahead and merge this without explanation/pro beyond the one I've mentioned.

**Comment by lyj0309** [comment]
> Can you say why you are updating these dependencies?
> 
> Is it just because they are old? Is there a security vulnerability you are fixing? Is there a bug that is affecting you?



> Can you say why you are updating these dependencies?
> 
> Is it just because they are old? Is there a security vulnerability you are fixing? Is there a bug that is affecting you?



> Can you say why you are updating these dependencies?
> 
> Is it just because they are old? Is there a security vulnerability you are fixing? Is there a bug that is affecting you?

#3041 fix letsencrypt certificate generated, and make the dependence version to a more stable release (Better readability?).

I want know what different from <https://hub.docker.com/r/distribution/distribution> between <https://hub.docker.com/_/registry> , and why the main branch is update, but the release stop.

**Comment by milosgajdos** [comment]
A ton of these have been updated as part of different PRs that got merged in. You might wanna close this @lyj0309

**Comment by lyj0309** [comment]
got it

**Pull request closed without merging**
