### PR TITLE
allow for optional S3 debugging -- closes issue #2043

### PR DESCRIPTION
**Pull request by vleurgat**
recent S3 storage issues made it very useful to be able to enable S3 API debug logging; contributing those simple enhancements back to the project; closes issue #2043 from 2016

### CODE REVIEW

**Comment by glance-** [comment]
This PR is extremly usefull when debugging issues with S3 backend against radosgw, so I would love to see this merged.

**Comment by glance-** [comment]
The only thing I'd suggest is that you squash those two commits together. They make no sense being two different commits, and as the tests fail with only the first commit will cause problems when running a git bisect.

**Comment by milosgajdos** [comment]
@vleurgat do you wanna rebase?

**Comment by flavianmissi** [comment]
Hi folks,
Since there's been no movement on the author's part I took the liberty to recreate this PR: https://github.com/distribution/distribution/pull/4076

**Comment by Jamstah** [comment]
Closed in #4076

**Pull request closed without merging**
