### PR TITLE
[backport release/2.7] Registry - make minimum TLS version user configurable

### PR DESCRIPTION
**Pull request by wy65701436**
Signed-off-by: J. Gregory Rebholz <gregrebholz@gmail.com>

### CODE REVIEW

**Comment by joaodrp** [comment]
As this introduces a new feature/config, we should probably do it with v2.8 instead.

**Comment by wy65701436** [comment]
but we can see it fixed a critucal secuity issue.

**Comment by gabrielcalderon** [comment]
The current release doesnt even include this changes... I have tried to get a new release with no luck

**Comment by milosgajdos** [comment]
@wy65701436 we should backport #3169 into `v2.X` instead and then work on making the long belated `v2.X` release.

**Review by milosgajdos — APPROVED** [review]

**Comment by milosgajdos** [comment]
Closing in favour of https://github.com/distribution/distribution/pull/3384

**Pull request closed without merging**
