### PR TITLE
vendor: github.com/sirupsen/logrus v1.9.3

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/sirupsen/logrus/compare/v1.8.1...v1.9.3

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]
PTAL @Jamstah @corhere @wy65701436 @joaodrp

**Comment by thaJeztah** [comment]
I was considering if we should use (e.g.) https://github.com/containerd/log as an abstraction for logrus (to potentially ease moving away), but not sure if it's worth the effort already (and to depend on that specific package). Probably best left for a later exercise.

**Comment by milosgajdos** [comment]
Yeah logging is one of the areas that will need looking into for v4.

Could also think about switching to `slog` so we ditch 3rd party deps completely 🤷‍♂️

**Comment by Jamstah** [comment]
This one is also in https://github.com/distribution/distribution/pull/4182

**Pull request merged**
