### PR TITLE
Accept list of strings in audience claim in token auth

### LINKED ISSUE #3735: JWT token is rejected if the audience claim is a list
Although the spec says the `aud` claim is a string, it's often represented as a list.

Currently, the registry fails with the following error: "error while unmarshalling raw token: json: cannot unmarshal array into Go struct field ClaimSet.aud of type string"

### PR DESCRIPTION
**Pull request by sagikazarmark**
Fixes #3735

### CODE REVIEW

**Review by milosgajdos — COMMENTED** [review]
The PR looks great. I'm a bit on the fence about introducing a new type just to serialize a simple struct field though. I understand you're trying to be a good citizen and make the encode/decode faster but it feels like premature optimisation to me. 🤔

**Comment by sagikazarmark** [comment]
It's not about serializing a simple field, but supporting both lists and single values in the token at the same time. If I replace `string` with `[]string`, tokens with a single string value will fail.

What do you suggest.

**Comment by milosgajdos** [comment]
Ah, yes you are right. I've misread that 😬 Let me think this through -- I was thinking, since it's localised to `token` package we could simply call that type `Audience`, but I understand you want to make it reusable should the need arise. Leave this with me for a bit.

**Comment by milosgajdos** [comment]
I believe you :) but it's also kinda interesting seeing the `golang-jwt` calling their type `ClaimsStrings`; I'm mulling over something like `AudienceStrings` 🤔

**Comment by sagikazarmark** [comment]
I can rename it if that's the only thing keeping you from accepting the PR. :)

But in general, I like to name types based on what they do, not how they are used.
The type allows deserializing a string into a string list.

An _instance_ of that type is going to be the audience.

I don't know if `ClaimStrings` is used for anything else, but there are other types in there with similar behavior that are used for multiple claims.

Anyway, let me know how to proceed and I'll update the PR.

**Comment by milosgajdos** [comment]
PR looks 👌 It's just me being silly here over naming...everytime I see `Weak*` I get ghosts of my `java` past haunting me

**Comment by sagikazarmark** [comment]
The alternative is getting rid of the entire implementation and replacing it with the JWT package. ;)

**Comment by milosgajdos** [comment]
Alright, lets call this type `AudienceList` -- there is no need to leak implementation details here in the name of the type. If we need the same type elsewhere we can type alias it or come up with some other way to deal with this. Once we rename the type I'm good with the change.

**Comment by sagikazarmark** [comment]
done

**Review by milosgajdos — APPROVED** [review]

**Review by corhere — APPROVED** [review]
LGTM

**Pull request merged**
