### PR TITLE
Add QingStor Storage Driver.

### PR DESCRIPTION
**Pull request by yangjunsss**
QingStor is a important Object Storage provider from [QingCloud](http://www.qingcloud.com) and the driver has been used for internal serveral months. Please make a review and merge.

### CODE REVIEW

**Comment by yangjunsss** [comment]
We can see there is build error here result from the dependence about [qingstor-sdk-go](https://github.com/yunify/qingstor-sdk-go). The driver depends on the ```qingstor-sdk-go``` which depends other vendor too, such as ```github.com/davecgh/go-spew``` ```github.com/pmezard/go-difflib``` and so on. Should I commit all codes under the ```vendor/github.com/yunify/qingstor-sdk-go ``` into the master??

**Comment by stevvooe** [comment]
Something seems wrong with this branch. It is showing a diff of 5 million lines of code. Could you get that sorted before we further review this?

**Comment by Martindlut** [comment]
Could you please help review this request ? Thanks! @stevvooe

**Comment by Martindlut** [comment]
I can send you a copy of credential files.

**Comment by Martindlut** [comment]
could you please tell me your email address?@dmp42

**Comment by yangjunsss** [comment]
Sorry, long time no see. Is there any news? Has the #2164 using plugin to install driver been done? @MartinForReal How do you solve the dependence things for now? Please confirm the driver code match with the current Registry master branch, tks.

**Comment by yangjunsss** [comment]
I can see there are 3 dependences in the driver code as below:
```golang
+github.com/opencontainers/go-digest a6d0ee40d4207ea02364bd3b9e8e77b9159ba1eb
+github.com/yunify/qingstor-sdk-go f6fc3668a87b1518fcb8b8f088234a1ca48f5111
+github.com/pengsrc/go-shared b98065a377794d577e2a0e32869378b9ce4b8952 
```

@MartinForReal  Is there possible that driver just only depends the `qingstor-sdk-go` library?  What are `go-digest` and `go-shared` used to?  Can we figure out a better way?

**Comment by MartinForReal** [comment]
@yangjunsss yunify/qingstor-sdk-go is not a battery-included project. I've created an issue https://github.com/docker/distribution/pull/2196

**Comment by MartinForReal** [comment]
@yangjunsss yunify/qingstor-sdk-go is not a battery-included project. I've created an issue https://github.com/docker/distribution/pull/2196

**Comment by yangjunsss** [comment]
@MartinForReal  Please fix the failed issue with latest sdk and merge the driver to upstream, good luck.

**Comment by dmp42** [comment]
@yangjunsss @MartinForReal are you guys still interested in working on this?

**Comment by MartinForReal** [comment]
@dmp42 @yangjunsss @stevvooe I've fixed build issue. But I still have no clue about the reason to jenkins build failure. Could you please help resolve this issue? Thanks!

@calvinyv Could you please sign up an account for distribution ci build process? Thx!

**Comment by dmp42** [comment]
Thanks @MartinForReal and @calvinyv

Ignore janky, it's broken.

@dmcgowan can you advise on the time needed to run system tests on a backend?

**Comment by kaleocheng** [comment]
seems this ticket has no update for a long time.  is there anyone still interested in working on this?

**Comment by kaleocheng** [comment]
update in here:  QingStor is compatible with S3.  so you can use S3 driver, e.g.:
```yaml
storage:
  s3:
    accesskey: xxxx 
    secretkey: xxxxx
    region: sh1a
    regionendpoint: s3.sh1a.qingstor.com
    bucket: registry
```

**Comment by Jamstah** [comment]
Closing because we are not currently accepting new storage drivers (https://github.com/distribution/distribution/blob/main/docs/storage-drivers/index.md#driver-contribution)

Also, this one is satisfied by the S3 support, which seems like a sensible way to use it.

**Pull request closed without merging**
