### PR TITLE
Switch to github.com/google/uuid

### PR DESCRIPTION
**Pull request by Jamstah**
Our own package wasn't adding anything.

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]
LGTM

**Comment by corhere** [comment]
> Our own package wasn't adding anything.

That I'm not so sure about. Our bespoke uuid package was introduced in #556 as a replacement of the predecessor to github.com/google/uuid of all things. Apparently backoff-retry on EPERM from the random source was a motivating factor. It probably didn't help that the uuid dependency at the time did this unconditionally:
https://github.com/distribution/distribution/blob/2317f721a3d8428215a2b65da4ae85212ed473b4/Godeps/_workspace/src/code.google.com/p/go-uuid/uuid/util.go#L11-L16
The `"github.com/google/uuid".NewString()` function is the same: read from the random source or panic. Random-source errors clearly were a problem:
- #782
- #792
so I am concerned that just doing the equivalent of reverting #556 is going to introduce regressions. Could we wrap google/uuid in the retry logic to retain the existing behaviour?

**Comment by milosgajdos** [comment]
I vaguely remember reading through that issue. I also found this comment by Stevoo kinda unresolved:

https://github.com/distribution/distribution/issues/782#issuecomment-126790975

Specifically, we never learnt what the real error actually was 🤷‍♂️

**Comment by Jamstah** [comment]
> so I am concerned that just doing the equivalent of reverting https://github.com/distribution/distribution/pull/556 is going to introduce regressions. Could we wrap google/uuid in the retry logic to retain the existing behaviour?

We _could_, but that was back in 2015 and I expect there have been many improvements since then.

Most of the places we create a uuid we don't have err in the return, so we couldn't fail more cleanly than panicking too.

Without a good understanding of why the workaround was needed, I think its sensible to remove it and see if we get any tickets during our beta period.

Just for fun, I created a billion uuids on my laptop using the google library. It took 5m39s and didn't panic once. I know that doesn't recreate whatever issue we had before, but I thought I'd try it.

**Review by corhere — APPROVED** [review]
Fair enough; I'm okay with scream-testing if you are

**Pull request merged**
