### PR TITLE
Restore documentation that was moved to docker docs repository (take 2)

### PR DESCRIPTION
**Pull request by thaJeztah**
alternative to https://github.com/distribution/distribution/pull/3307, this time trying to preserve git history.

More cleaning up may have to be done after this (removing some wording that may be specific to how the docs were used in docs.docker.com

## 1. Revert "Remove old documentation source, add README on migration"

this reverts commit https://github.com/docker/distribution/commit/da8bcbb3029b79ad25cb8cb5da166e967dd3bf75
there were some conflicts, because some docs were restored

## 2. Integrate documentation from the docker documentation repository

strategy taken:

```bash
# install filter-repo (https://github.com/newren/git-filter-repo/blob/main/INSTALL.md)
brew install git-filter-repo

cd ~/projects

# create a temporary clone of the documentation repo
git clone https://github.com/docker/docker.github.io.git distribution_docs
cd distribution_docs

# create branch to work with
git checkout -b migrate_distribution_docs

# remove all code, except for the "registry" directory
git filter-repo --path registry

# move the files to match the target repository
git mv registry docs

# go to the target github.com/distribution/distribution repository
cd ~/projects/distribution

# create a branch to work with
git checkout -b restore_docs2

# add the temporary repository as an upstream and make sure it's up-to-date
git remote add distribution_docs ~/projects/distribution_docs
git fetch distribution_docs

# merge the upstream code, rewriting "registry/" to "docs/"
git merge --allow-unrelated-histories --signoff -S distribution_docs/migrate_distribution_docs
```

Merge conflicts because likely changes were made in between, and didn't apply cleanly on the "restored" docs.
All conflicts seemed to be in the docs that were removed (and restored in the first commit), so I took the
versions of the docker documentation repository as "leading"

```
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both added:      docs/compatibility.md
	both added:      docs/deploying.md
	both added:      docs/deprecated.md
	both added:      docs/garbage-collection.md
	both added:      docs/glossary.md
	both added:      docs/help.md
	both added:      docs/images/notifications.png
	both added:      docs/index.md
	both added:      docs/insecure.md
	both added:      docs/introduction.md
	both added:      docs/migration.md
	both added:      docs/notifications.md
	both added:      docs/recipes/apache.md
	both added:      docs/recipes/index.md
	both added:      docs/recipes/mirror.md
	both added:      docs/recipes/nginx.md
	both added:      docs/recipes/osx-setup-guide.md
	both added:      docs/recipes/osx/config.yml
	both added:      docs/storage-drivers/azure.md
	both added:      docs/storage-drivers/filesystem.md
	both added:      docs/storage-drivers/gcs.md
	both added:      docs/storage-drivers/index.md
	both added:      docs/storage-drivers/inmemory.md
	both added:      docs/storage-drivers/oss.md
	both added:      docs/storage-drivers/s3.md
	both added:      docs/storage-drivers/swift.md

no changes added to commit (use "git add" and/or "git commit -a")
```

# 3. Remove docs.docker.com "include" directives

These were used to add a banner on pages on docs.docker.com; removing, as they serve no purpose in this repository

# 4. Remove code related to building docs with Hugo

This code was outdated and no longer maintained, and mainly used to pre-flight docs changes before publishing to docs.docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
DCO checks will fail because the docker documentation repo doesn't enforce DCO sign-offs

**Review by milosgajdos — CHANGES_REQUESTED** [review]
Mammoth effort. Thanks @thaJeztah. One thing I noticed, there are references in the docs to the old distribution org i.e. `docker/distribution`. It would be good if we could rewrite those to the new org `distribution/distribution`.

**Comment by justincormack** [comment]
@thaJeztah rewriting docker/distribution to distribution/distribution would be good.

@caniszczyk whats the procedure for us doing a one time bypass of DCO for a historical import of docs?

**Comment by thaJeztah** [comment]
I think there may have been updates in the docs repository since this was opened, but I can do a quick check to re-do this PR and update it with the latest changes, and do some initial `s/docker/distribution/`

**Comment by thaJeztah** [comment]
@milosgajdos @justincormack I updated this PR;

- re-did the migration to get the latest changes from the docs repository
- updated URLs from docker/distribution to distribution/distribution (some instructions may still need some TLC to account for the change to go modules, but keeping that for a future exercise)
- removed some "docker" branding ("docker registry -> registry"), but there's more things to clean up in that area.


> @caniszczyk whats the procedure for us doing a one time bypass of DCO for a historical import of docs?

Do we have an answer for this one? Copied the list of failing commits below;


<details>

- Commit sha: db6444a, Author: Akihiro Suda, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: f0fe5c3, Author: Akihiro Suda, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: b98fb58, Author: Aleksejs Sinicins, Committer: Aleksejs Sinicins; The sign-off is missing.
- Commit sha: 2aa6e2a, Author: Andrew Lively, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: e61eb68, Author: Anian Z, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: f89f086, Author: Anne Henmi, Committer: GitHub; The sign-off is missing.
- Commit sha: 43b914b, Author: Anne Henmi, Committer: GitHub; The sign-off is missing.
- Commit sha: a49afdb, Author: Ben De St Paer-Gotch, Committer: GitHub; The sign-off is missing.
- Commit sha: 1777a5b, Author: Ben De St Paer-Gotch, Committer: GitHub; The sign-off is missing.
- Commit sha: f2f9b29, Author: Ben Emamian, Committer: GitHub; The sign-off is missing.
- Commit sha: 82530e5, Author: Bhavin Gandhi, Committer: Misty Stanley-Jones; Expected "Bhavin Gandhi bhavin192@users.noreply.github.com", but got "Bhavin Gandhi bhavin7392@gmail.com".
- Commit sha: 547233e, Author: Bill, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 864905c, Author: Chaos John, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 0620562, Author: Cheng Zheng, Committer: GitHub; The sign-off is missing.
- Commit sha: eaeb316, Author: Dan Fredell, Committer: GitHub; The sign-off is missing.
- Commit sha: 576f4fc, Author: Daniel Helfand, Committer: GitHub; The sign-off is missing.
- Commit sha: d616708, Author: Dawn W Docker, Committer: Dawn W Docker; The sign-off is missing.
- Commit sha: c7dab7f, Author: Denis Andrejew, Committer: GitHub; The sign-off is missing.
- Commit sha: ff78664, Author: E. M. Bray, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: 90a402d, Author: Emmanuel Briney, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 943860f, Author: Etki, Committer: GitHub; The sign-off is missing.
- Commit sha: 5e3911c, Author: Eugene Lubarsky, Committer: GitHub; The sign-off is missing.
- Commit sha: 3d14741, Author: Gaetan, Committer: Misty Stanley-Jones; Expected "Gaetan gdevillele@gmail.com", but got "Gaetan de Villele gdevillele@gmail.com".
- Commit sha: cc71bed, Author: Gaetan, Committer: John Mulhausen; Expected "Gaetan gdevillele@gmail.com", but got "Gaetan de Villele gdevillele@gmail.com".
- Commit sha: b263563, Author: gary schaetz, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: 1003ce3, Author: ghodsizadeh, Committer: GitHub; The sign-off is missing.
- Commit sha: 40f4476, Author: Giovanni Toraldo, Committer: GitHub; The sign-off is missing.
- Commit sha: dfcc7bc, Author: Jakob Ackermann, Committer: GitHub; The sign-off is missing.
- Commit sha: 3d71710, Author: jerae-duffin, Committer: GitHub; The sign-off is missing.
- Commit sha: 1b6da36, Author: Jim Galasyn, Committer: GitHub; The sign-off is missing.
- Commit sha: aed6cb2, Author: Jim Galasyn, Committer: GitHub; The sign-off is missing.
- Commit sha: c60e710, Author: Jim Galasyn, Committer: GitHub; The sign-off is missing.
- Commit sha: 82998e1, Author: Jim Galasyn, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: cf36ad3, Author: Jim Galasyn, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: a250062, Author: Jim Galasyn, Committer: Jim Galasyn; The sign-off is missing.
- Commit sha: cc72cef, Author: Joao Fernandes, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: 042cf0f, Author: Joao Fernandes, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: ee6aa7d, Author: Joao Fernandes, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: 00d1f82, Author: Joao Fernandes, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: 3d5f8b0, Author: Joao Fernandes, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 198ebad, Author: Joao Fernandes, Committer: GitHub; The sign-off is missing.
- Commit sha: 9e3c43c, Author: John Mulhausen, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: b3b099f, Author: John Mulhausen, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: 856daca, Author: John Mulhausen, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: 9204a64, Author: John Mulhausen, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: 50bd0cc, Author: John Mulhausen, Committer: GitHub; The sign-off is missing.
- Commit sha: bd9f8c7, Author: John Mulhausen, Committer: GitHub; The sign-off is missing.
- Commit sha: 8e8290b, Author: John Mulhausen, Committer: GitHub; The sign-off is missing.
- Commit sha: e63f595, Author: John Mulhausen, Committer: GitHub; The sign-off is missing.
- Commit sha: 908a1f1, Author: John Mulhausen, Committer: GitHub; The sign-off is missing.
- Commit sha: cb3f2ac, Author: John Mulhausen, Committer: GitHub; The sign-off is missing.
- Commit sha: a8dac1a, Author: John Mulhausen, Committer: GitHub; The sign-off is missing.
- Commit sha: 8b93c50, Author: Jonas Hecht, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 1f640d1, Author: Jonas Hecht, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: c8d82bb, Author: Jonas Hecht, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 5cf9203, Author: Jonathan Lee, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: 39a8fcd, Author: Jonathan Lee, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: a92ed35, Author: Julien Bordellier, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: b922019, Author: Kevin Robatel, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 582d8e6, Author: L-Hudson, Committer: GitHub; The sign-off is missing.
- Commit sha: a6edcad, Author: Lachlan Cooper, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: b588970, Author: Lenny Linux, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: f189917, Author: Lenny Linux, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: b19b19c, Author: leonstrand, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: f497e79, Author: mallchin, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: bfd7156, Author: Maria Bermudez, Committer: GitHub; The sign-off is missing.
- Commit sha: 7eac5fa, Author: Maria Bermudez, Committer: GitHub; The sign-off is missing.
- Commit sha: 2df4504, Author: Maria Bermudez, Committer: Maria Bermudez; The sign-off is missing.
- Commit sha: b9c4182, Author: Maria Bermudez, Committer: Maria Bermudez; The sign-off is missing.
- Commit sha: 88038ff, Author: Maria Bermudez, Committer: Maria Bermudez; The sign-off is missing.
- Commit sha: f04f620, Author: Maria Bermudez, Committer: Maria Bermudez; The sign-off is missing.
- Commit sha: 71d02b1, Author: Maria Bermudez, Committer: Maria Bermudez; The sign-off is missing.
- Commit sha: 50dacc5, Author: Maria Bermudez, Committer: Maria Bermudez; The sign-off is missing.
- Commit sha: b0bb843, Author: Maria Bermudez, Committer: GitHub; The sign-off is missing.
- Commit sha: 2fda032, Author: Maria Bermudez, Committer: GitHub; The sign-off is missing.
- Commit sha: 01ceef9, Author: Maria Bermudez, Committer: Maria Bermudez; The sign-off is missing.
- Commit sha: 3be1cde, Author: Maria Bermudez, Committer: GitHub; The sign-off is missing.
- Commit sha: 414cebd, Author: Maria Bermudez, Committer: GitHub; The sign-off is missing.
- Commit sha: 1fa75f3, Author: Matthew Balvanz, Committer: GitHub; The sign-off is missing.
- Commit sha: eb2763d, Author: Michal Guerquin, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: f0a62cc, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 734f334, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: e9de6f2, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: d4f01b8, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: be48783, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: a56d36f, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: b2da4f3, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: dd41410, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 0fb207c, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 677eaaa, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 8c922b0, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 82eb4bc, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 6f78566, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: eb77e2f, Author: Misty Stanley-Jones, Committer: John Mulhausen; Can not find "Misty Stanley-Jones misty@apache.org", in ["Brian Goff cpuguy83@gmail.com", "Brian Goff cpuguy83@gmail.com", "Victor Vieux victorvieux@gmail.com", "French Ben frenchben@docker.com", "French Ben frenchben@docker.com", "Victoria Bialas victoria.bialas@docker.com", "French Ben frenchben@docker.com", "French Ben frenchben@docker.com", "French Ben frenchben@docker.com", "Victoria Bialas victoria.bialas@docker.com", "Victoria Bialas victoria.bialas@docker.com"].
- Commit sha: fde5228, Author: Misty Stanley-Jones, Committer: GitHub; The sign-off is missing.
- Commit sha: ed56794, Author: Misty Stanley-Jones, Committer: GitHub; The sign-off is missing.
- Commit sha: 7c5b1e6, Author: Misty Stanley-Jones, Committer: GitHub; The sign-off is missing.
- Commit sha: 8ac7579, Author: Misty Stanley-Jones, Committer: GitHub; The sign-off is missing.
- Commit sha: 31619ae, Author: Misty Stanley-Jones, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: c6f6c44, Author: Misty Stanley-Jones, Committer: Victoria Bialas; The sign-off is missing.
- Commit sha: a108893, Author: Misty Stanley-Jones, Committer: GitHub; The sign-off is missing.
- Commit sha: 9360075, Author: Misty Stanley-Jones, Committer: GitHub; The sign-off is missing.
- Commit sha: f1fb068, Author: Misty Stanley-Jones, Committer: GitHub; The sign-off is missing.
- Commit sha: 09d8e4b, Author: Misty Stanley-Jones, Committer: GitHub; The sign-off is missing.
- Commit sha: 560471b, Author: Muesli, Committer: GitHub; The sign-off is missing.
- Commit sha: 9042088, Author: Nat Zimmermann, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: e7dc768, Author: Novak Ivanovski, Committer: GitHub; The sign-off is missing.
- Commit sha: fdb1abd, Author: ollypom, Committer: ollypom; The sign-off is missing.
- Commit sha: e92760a, Author: Oscar Caballero, Committer: Oscar Caballero; The sign-off is missing.
- Commit sha: f9d531c, Author: paigehargrave, Committer: GitHub; The sign-off is missing.
- Commit sha: c738615, Author: paigehargrave, Committer: GitHub; The sign-off is missing.
- Commit sha: 2d32aa4, Author: Pascal Borreli, Committer: Pascal Borreli; The sign-off is missing.
- Commit sha: ea84d17, Author: Pavel Antonov, Committer: Pavel Antonov; The sign-off is missing.
- Commit sha: 8112d01, Author: Per Lundberg, Committer: GitHub; The sign-off is missing.
- Commit sha: 09fdbf4, Author: Peter Dave Hello, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: a59d321, Author: Peter Kokot, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 23c116b, Author: Peter Kokot, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 55aec8a, Author: Pieter Scheffers, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: a954922, Author: Robert Steward, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: f01d83d, Author: ROY, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: b5bbca9, Author: Sean P. Kane, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 267e231, Author: Sebastiaan van Stijn, Committer: GitHub; Can not find "Sebastiaan van Stijn thaJeztah@users.noreply.github.com", in ["Sebastiaan van Stijn github@gone.nl", "Sebastiaan van Stijn github@gone.nl", "Sebastiaan van Stijn github@gone.nl"].
- Commit sha: b338d2f, Author: Sebastiaan van Stijn, Committer: GitHub; Expected "Sebastiaan van Stijn thaJeztah@users.noreply.github.com", but got "Sebastiaan van Stijn github@gone.nl".
- Commit sha: 4f582ad, Author: Shiela M Parker, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 0a7648e, Author: Stefan Lörwald, Committer: GitHub; The sign-off is missing.
- Commit sha: 7cf8dc7, Author: Steven Hanna, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: 955f7ef, Author: sun jian, Committer: GitHub; The sign-off is missing.
- Commit sha: f580993, Author: syntaxkim, Committer: GitHub; The sign-off is missing.
- Commit sha: 1b6e19d, Author: T N, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: 78242c7, Author: t-eimizu, Committer: GitHub; The sign-off is missing.
- Commit sha: 8edea60, Author: Tobias Fuhrimann, Committer: GitHub; The sign-off is missing.
- Commit sha: 5a2e1bf, Author: Trapier Marshall, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: cb2a09f, Author: Usha Mandya, Committer: GitHub; The sign-off is missing.
- Commit sha: dc7801c, Author: Usha Mandya, Committer: Usha Mandya; The sign-off is missing.
- Commit sha: c2bbc7e, Author: Vega Chou, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 3c1aeeb, Author: Victoria Bialas, Committer: GitHub; Can not find "Victoria Bialas londoncalling@users.noreply.github.com", in ["Victoria Bialas victoria.bialas@docker.com", "Victoria Bialas victoria.bialas@docker.com"].
- Commit sha: e4f126c, Author: Vidar, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: fd9fc03, Author: Vidar, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 9161e93, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: a5b2b63, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 2c19d1c, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: a6fc3fa, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 78d2501, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 528d227, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 4da4fc0, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: efa76b9, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: bbbafb0, Author: Wang Jie, Committer: John Mulhausen; The sign-off is missing.
- Commit sha: d18e3a6, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: e98a162, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 3ae7d9c, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: aa2955a, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: c1950e1, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: aa6e697, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 5096a16, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: e95522e, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: b597546, Author: Wang Jie, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: 1edd9dc, Author: Wang Jie, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: 947af10, Author: Wang Jie, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: 35cca3f, Author: Wang Jie, Committer: Gwendolynne Barr; The sign-off is missing.
- Commit sha: 4a9ec81, Author: Wang Jie, Committer: Gwendolynne Barr; The sign-off is missing.
- Commit sha: e80e5f2, Author: Wang Jie, Committer: Joao Fernandes; The sign-off is missing.
- Commit sha: 6508f12, Author: Wassim Dhif, Committer: Misty Stanley-Jones; The sign-off is missing.
- Commit sha: c594eb1, Author: Xueshan Feng, Committer: GitHub; The sign-off is missing.
- Commit sha: 675ffdb, Author: Yannick Fricke, Committer: Joao Fernandes; The sign-off is missing.


</details>

**Review by milosgajdos — APPROVED** [review]

**Comment by caniszczyk** [comment]
This is a corner case and CNCF is OK if you bring in historic commits w/o DCO because at the time the project wasn't part of CNCF. Thanks for giving us the heads us

**Comment by thaJeztah** [comment]
Thanks for checking, Chris!

**Review by deleteriousEffect — CHANGES_REQUESTED** [review]
Why is the number of commits so huge? Is that going to look weird in `git log`?


The diff looks great though.

image

**Comment by thaJeztah** [comment]
The number of commits is large because this extracts the docs from the docker documentation repository, preserving history (so original contributors)

**Comment by deleteriousEffect** [comment]
> The number of commits is large because this extracts the docs from the docker documentation repository, preserving history (so original contributors)

@thaJeztah right, thank you. 

I approve, wonderful work on this :rocket:

**Review by deleteriousEffect — APPROVED** [review]

**Comment by milosgajdos** [comment]
Now that we have @caniszczyk permission to merge this in even though DCO fails on some commits I'm merging this in

**Comment by thaJeztah** [comment]
Thanks!

**Pull request merged**
