### PR TITLE
change log level from debug to error when error

### PR DESCRIPTION
**Pull request by liubin**

### CODE REVIEW

**Comment by Jamstah** [comment]
Isn't this error bubbled up to be handled further up the stack? What if the caller knows how to handle the error correctly and it doesn't need to be logged?

**Comment by Jamstah** [comment]
Also, the caller is likely to also log the error, which would mean we log it twice.

**Comment by milosgajdos** [comment]
> Also, the caller is likely to also log the error, which would mean we log it twice.

With a different context, indeed.

**Comment by liubin** [comment]
@Jamstah @milosgajdos sure it will be logged twice, one is in the `GetBlob` function with debug level, and one is here line 626 logged as an error

https://github.com/distribution/distribution/blob/f7b3869062dbbfdf0260d223bac90a69418c3028/registry/handlers/app.go#L624-L629

The example log will be:

```
DEBU[0223] unexpected error getting blob HTTP handler: <ERROR-MESSAGE-FROM-GetBlob>  go.version=go1.20.3 http.request.host="30.30.147.212:5000" http.request.id=4135d152-3be1-4cb7-a415-9dfbd02c4f72 http.request.method=HEAD http.request.remoteaddr="182.168.2.7:33326" http.request.uri="/v2/coredns/blobs/sha256:d92bdee797857f997be3c92988a15c196893cbbd6d5db2aadcdffd2a98475d2d" http.request.useragent="docker/dev go/go1.19.2 git-commit/c218211012 kernel/5.4.0-125-generic os/linux arch/amd64 UpstreamClient(Docker-Client/22.06.0-beta.0-167-gd0bd373986 \\(linux\\))" instance.id=1fac23db-8d7a-48e4-962e-f8560935c341 service=registry vars.digest="sha256:d92bdee797857f997be3c92988a15c196893cbbd6d5db2aadcdffd2a98475d2d" vars.name=coredns version=v3.0.0+unknown
ERRO[0223] response completed with error                 err.code=unknown err.detail="<ERROR-MESSAGE-FROM-GetBlob>" err.message="unknown error" go.version=go1.20.3 http.request.host="30.30.147.212:5000" http.request.id=4135d152-3be1-4cb7-a415-9dfbd02c4f72 http.request.method=HEAD http.request.remoteaddr="182.168.2.7:33326" http.request.uri="/v2/coredns/blobs/sha256:d92bdee797857f997be3c92988a15c196893cbbd6d5db2aadcdffd2a98475d2d" http.request.useragent="docker/dev go/go1.19.2 git-commit/c218211012 kernel/5.4.0-125-generic os/linux arch/amd64 UpstreamClient(Docker-Client/22.06.0-beta.0-167-gd0bd373986 \\(linux\\))" http.response.contenttype=application/json http.response.duration=303.424541ms http.response.status=500 http.response.written=70 instance.id=1fac23db-8d7a-48e4-962e-f8560935c341 service=registry vars.digest="sha256:d92bdee797857f997be3c92988a15c196893cbbd6d5db2aadcdffd2a98475d2d" vars.name=coredns version=v3.0.0+unknown
182.168.2.7 - - [07/Oct/2023:12:03:59 +0800] "HEAD /v2/coredns/blobs/sha256:d92bdee797857f997be3c92988a15c196893cbbd6d5db2aadcdffd2a98475d2d HTTP/1.1" 500 70 "" "docker/dev go/go1.19.2 git-commit/c218211012 kernel/5.4.0-125-generic os/linux arch/amd64 UpstreamClient(Docker-Client/22.06.0-beta.0-167-gd0bd373986 \\(linux\\))"

```

**Comment by Jamstah** [comment]
If it is already logged by the app handler, why is it better to change the level?

**Comment by liubin** [comment]
@Jamstah yes, it's better to keep current log level.

**Pull request closed without merging**
