### PR TITLE
Update Prometheus client library

### PR DESCRIPTION
**Pull request by SuperQ**
Update to the current major release of the Prometheus client library.

### CODE REVIEW

**Comment by manishtomar** [comment]
Thanks! I am going to test this out and let you know.

**Comment by dmcgowan** [comment]
Ping @manishtomar, this PR is still green, let me know if it looks good and I can re-kick the tests to verify.

**Comment by olegburov** [comment]
@SuperQ could you please rebase and bump the library to the latest https://github.com/prometheus/client_golang/releases/tag/v1.7.1?

**Comment by SuperQ** [comment]
@olegburov Done

**Comment by milosgajdos** [comment]
Unfortunately, we need to rebase again @SuperQ

**Comment by SuperQ** [comment]
I'm just going to drop this, since it's an indirect dependency now.

**Pull request closed without merging**
