### PR TITLE
vendor: github.com/prometheus/client_golang v1.12.1

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@milosgajdos ptal

**Review by milosgajdos — COMMENTED** [review]
`go.sum` looks a bit wild....have we run  `go mod tidy`?

**Comment by thaJeztah** [comment]
Yup; ran `go mod tidy`; it's probably because some of those dependencies are used by a _LOT_ of other dependencies, and all of them use different versions. e.g.;

```bash
go mod graph | grep ' cloud.google.com/go@'
golang.org/x/oauth2@v0.0.0-20210514164344-f6687ab2804c cloud.google.com/go@v0.65.0
google.golang.org/api@v0.30.0 cloud.google.com/go@v0.62.0
golang.org/x/oauth2@v0.0.0-20200107190931-bf48bf16ab8d cloud.google.com/go@v0.34.0
google.golang.org/grpc@v1.21.0 cloud.google.com/go@v0.26.0
cloud.google.com/go/storage@v1.10.0 cloud.google.com/go@v0.57.0
google.golang.org/api@v0.29.0 cloud.google.com/go@v0.56.0
google.golang.org/grpc@v1.19.0 cloud.google.com/go@v0.26.0
google.golang.org/grpc@v1.20.1 cloud.google.com/go@v0.26.0
cloud.google.com/go/bigquery@v1.8.0 cloud.google.com/go@v0.57.0
google.golang.org/api@v0.28.0 cloud.google.com/go@v0.56.0
golang.org/x/oauth2@v0.0.0-20190226205417-e64efc72b421 cloud.google.com/go@v0.34.0
cloud.google.com/go/bigquery@v1.4.0 cloud.google.com/go@v0.52.0
cloud.google.com/go/datastore@v1.1.0 cloud.google.com/go@v0.52.0
cloud.google.com/go/pubsub@v1.2.0 cloud.google.com/go@v0.52.0
cloud.google.com/go/storage@v1.6.0 cloud.google.com/go@v0.53.0
google.golang.org/api@v0.22.0 cloud.google.com/go@v0.38.0
cloud.google.com/go/storage@v1.8.0 cloud.google.com/go@v0.57.0
google.golang.org/api@v0.24.0 cloud.google.com/go@v0.56.0
google.golang.org/api@v0.20.0 cloud.google.com/go@v0.38.0
google.golang.org/grpc@v1.23.0 cloud.google.com/go@v0.26.0
cloud.google.com/go/storage@v1.5.0 cloud.google.com/go@v0.50.0
google.golang.org/api@v0.15.0 cloud.google.com/go@v0.38.0
google.golang.org/api@v0.17.0 cloud.google.com/go@v0.38.0
google.golang.org/api@v0.18.0 cloud.google.com/go@v0.38.0
golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45 cloud.google.com/go@v0.34.0
cloud.google.com/go/bigquery@v1.7.0 cloud.google.com/go@v0.56.0
cloud.google.com/go/bigquery@v1.0.1 cloud.google.com/go@v0.44.2
cloud.google.com/go/datastore@v1.0.0 cloud.google.com/go@v0.44.1
cloud.google.com/go/pubsub@v1.0.1 cloud.google.com/go@v0.45.1
cloud.google.com/go/storage@v1.0.0 cloud.google.com/go@v0.46.3
cloud.google.com/go/bigquery@v1.3.0 cloud.google.com/go@v0.46.3
cloud.google.com/go/pubsub@v1.1.0 cloud.google.com/go@v0.46.3
golang.org/x/oauth2@v0.0.0-20191202225959-858c2ad4c8b6 cloud.google.com/go@v0.34.0
cloud.google.com/go/pubsub@v1.3.1 cloud.google.com/go@v0.54.0
google.golang.org/api@v0.8.0 cloud.google.com/go@v0.38.0
google.golang.org/grpc@v1.21.1 cloud.google.com/go@v0.26.0
google.golang.org/api@v0.7.0 cloud.google.com/go@v0.38.0
google.golang.org/api@v0.9.0 cloud.google.com/go@v0.38.0
google.golang.org/api@v0.14.0 cloud.google.com/go@v0.38.0
google.golang.org/api@v0.13.0 cloud.google.com/go@v0.38.0
cloud.google.com/go/bigquery@v1.5.0 cloud.google.com/go@v0.53.0
google.golang.org/api@v0.19.0 cloud.google.com/go@v0.38.0
```

**Comment by thaJeztah** [comment]
I can update the main branch to go1.17/go1.18 if we think that makes sense (as go1.16 is EOL); that cleans up some of the go.mod files in vendor

**Comment by thaJeztah** [comment]
Opened https://github.com/distribution/distribution/pull/3643 to update the go version; I'll rebase this one once that's merged.

**Comment by thaJeztah** [comment]
rebased 👍

**Comment by milosgajdos** [comment]
Waiting for CI

**Review by milosgajdos — APPROVED** [review]

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
