### PR TITLE
[release/2.8 backport] replace rsc.io/letsencrypt in favour of golang.org/x/crypto

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/docker/distribution/pull/2926

As per the readme over [here](https://github.com/rsc/letsencrypt/blob/master/README), it's recommended to use acme/autocerts.

closes https://github.com/docker/distribution/issues/1976

### CODE REVIEW

**Comment by thaJeztah** [comment]
@dmcgowan @manishtomar PTAL

**Comment by dmcgowan** [comment]
We don't have any test automation for Let's encrypt today. How is this being verified on the 2.7 branch?

**Comment by milosgajdos** [comment]
@thaJeztah can you rebase this, please?

**Comment by thaJeztah** [comment]
I rebased this one, but per discussion above, if there's risk involved in this change, and with (I think) version v3.0.0 (main branch) starting to take shape, I think it would be ok to close this one and just acknowledge that the current implementation in v2.7.x is broken.

**Comment by dmcgowan** [comment]
My concern was more just, was this tested and verified. I don't have any specific concern over risk since it is not in a good shape today anyway

**Comment by milosgajdos** [comment]
I'm happy to close this. I think there are few people reporting letsencrypt support on the long overdue 2.7 release, but if we can't make sure this works I say let's chuck it and see if anyone screams. We can always reopen it and pick it up again

**Comment by thaJeztah** [comment]
@milosgajdos IIUC, current implementation in 2.7 was broken, so I guess it can't be worse than that, but it'd be good to test it (haven't found time to do so, but if you do have time to give it a spin)

**Comment by eclipseo** [comment]
Could this be merged for another point release?

**Comment by milosgajdos** [comment]
@thaJeztah should we close this? Given it was opened against the `v2.7` branch and we won't be adding it into any `v2.X` branches

**Comment by milosgajdos** [comment]
@thaJeztah do you mind closing this?

**Comment by milosgajdos** [comment]
@thaJeztah let's close this

**Comment by thaJeztah** [comment]
yup SGTM

**Pull request closed without merging**
