### PR TITLE
registry/api: move all errors to "errcode" package, and split "Register" to internal / exported

### PR DESCRIPTION
**Pull request by thaJeztah**
Move all errors to the errcode package

### CODE REVIEW

**Comment by thaJeztah** [comment]
This was an attempt not having to import the registry _api_ (just to be able to handle errors it returns); https://github.com/docker/cli/blob/f74f88445f8b23fe4804f1072e5f376cfbe46487/cli/registry/client/fetcher.go#L204-L206


But I may need more to be moved, e.g. `v2.URLBuilder` is also in some places; https://github.com/distribution/distribution/blob/90939f1173f65356e724f398793b4d7239a49595/registry/api/v2/urls.go#L38

**Comment by milosgajdos** [comment]
Oh, right. Yeah, I'd love this project to be more modular(ised), too.

**Review by milosgajdos — APPROVED** [review]

**Comment by thaJeztah** [comment]
Yeah, some parts are really coupled (in this case, the API server _implementation_ (gorilla/mux) leaks all the way into the client, which always felt "off".

The errors in general are hard to work with (and I'm not even sure if we handle them correctly everywhere); I know where some of the ideas for these "structured" errors originated from at the time, but they're lacking in utilities to handle them.

**Review by DavidSpek — APPROVED** [review]
LGTM

**Pull request merged**
