### PR TITLE
go.mod: github.com/Azure/go-autorest/autorest v0.11.24

### PR DESCRIPTION
**Pull request by thaJeztah**
Update the indirect dependency to remove the transitional github.com/form3tech-oss/jwt-go
dependency from the dependency graph.

Updates:

- github.com/Azure/go-autorest/autorest v0.11.24: https://github.com/Azure/go-autorest/compare/autorest/v0.11.20...autorest/v0.11.24
- github.com/Azure/go-autorest/autorest/adal v0.9.18: https://github.com/Azure/go-autorest/compare/autorest/adal/v0.9.15...autorest/adal/v0.9.18
- github.com/golang-jwt/jwt v4.2.0: https://github.com/golang-jwt/jwt/compare/v4.0.0...v4.2.0
- golang.org/x/crypto v0.0.0-20211215153901-e495a2d5b3d3: https://github.com/golang/crypto/compare/32db794688a5...e495a2d5b3d3

Before this:

    go mod graph | grep 'jwt'
    github.com/Azure/go-autorest/autorest/adal@v0.9.15 github.com/golang-jwt/jwt/v4@v4.0.0
    github.com/Azure/go-autorest/autorest/adal@v0.9.13 github.com/form3tech-oss/jwt-go@v3.2.2+incompatible

After this:

    go mod graph | grep 'jwt'
    github.com/Azure/go-autorest/autorest@v0.11.24 github.com/golang-jwt/jwt/v4@v4.2.0
    github.com/Azure/go-autorest/autorest/adal@v0.9.18 github.com/golang-jwt/jwt/v4@v4.0.0

### CODE REVIEW

**Comment by milosgajdos** [comment]
Need to wait for #3576 and then rebase.

**Review by milosgajdos — APPROVED** [review]

**Comment by milosgajdos** [comment]
We need to rebase @thaJeztah

**Comment by thaJeztah** [comment]
Thx for the ping; rebased 👍

**Comment by thaJeztah** [comment]
hm.. for some reason GitHub action doesn't kick-in (stuck in pending); let me try to close/reopen

**Comment by milosgajdos** [comment]
I've tagged a few more maintainers 🤞

**Review by joaodrp — APPROVED** [review]

**Comment by joaodrp** [comment]
LGTM!

**Pull request merged**
