### PR TITLE
Add support for modern ACME

### PR DESCRIPTION
**Pull request by lavalleeale**
Similar to #2926 but also implements allowing custom ACME server. See #3749 #3041

### CODE REVIEW

**Comment by DavidSpek** [comment]
@lavalleeale You might want to have this target the main branch or also create a PR for the main branch so that this work doesn't get reverted in the next release of distribution.

**Comment by milosgajdos** [comment]
Yeah, I'd target the `main`; I dont think we'll merge this to `2.8`

**Comment by lavalleeale** [comment]
Ok, I was just hoping for a way to use `2.8` with acme since the current implementation is unusable unless there is something I'm missing? Because of that, I would argue it is not a breaking change since no current setup can use letsencrypt anyway.

**Comment by milosgajdos** [comment]
Wasn't one of the original issues around it that the `rsc.io` dependency that we use in the older version just didn't work well? Either way, we have decided not to merge anything to `2.8` other than security fixes - it just diverges the focus away from `v3` release.

**Comment by milosgajdos** [comment]
With https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1 out now, I'm closing this PR as it won't be merged into `2.x` branch. All the further development is going into getting a stable `v3` release out next year.

**Pull request closed without merging**
