### PR TITLE
vendor: github.com/opencontainers/image-spec v1.1.0

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/opencontainers/image-spec/compare/v1.0.2...v1.1.0

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by milosgajdos** [comment]
Do we want to merge RC dependency? You know what happened last time OCI decided to cut a release....I'd hold back until stable release is cut 😄

**Comment by brackendawson** [comment]
#3834 included this change (and requires it). I'm not sure why the project would move to an unstable release unless it's necessary.

**Comment by thaJeztah** [comment]
Rebased and updated to v1.1.0

**Review by milosgajdos — APPROVED** [review]

**Pull request merged**
