### PR TITLE
Add cncf-distribution-maintainers@cncf.io to maintainers file

### PR DESCRIPTION
**Pull request by SteveLasker**
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]

**Comment by thaJeztah** [comment]
If this is the intended address to report security issues, then this section should also be updated; https://github.com/distribution/distribution/blob/main/CONTRIBUTING.md#reporting-security-issues

**Comment by thaJeztah** [comment]
> If this is the intended address to report security issues, then this section should also be updated; https://github.com/distribution/distribution/blob/main/CONTRIBUTING.md#reporting-security-issues

Ah, never mind, I missed https://github.com/distribution/distribution/pull/3549

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by SteveLasker** [comment]
Converting to draft to put this on hold as the email is now bouncing :(
One the service desk ticket is resolved, I'll convert back.

**Comment by milosgajdos** [comment]
Ouch, I've clicked merge on https://github.com/distribution/distribution/pull/3549

Oh, well

**Pull request merged**
