### PR TITLE
[release/2.7] vendor: github.com/opencontainers/image-spec v1.0.2

### PR DESCRIPTION
**Pull request by thaJeztah**
(previous version vendored was v1.0.0)

full diff: https://github.com/opencontainers/image-spec/compare/ab7389ef9f50030c9b245bc16b981c7ddf192882...v1.0.2

### CODE REVIEW

**Comment by thaJeztah** [comment]
@milosgajdos PTAL

**Comment by thaJeztah** [comment]
(not sure if we need it, as we don't use this field currently)

**Comment by milosgajdos** [comment]
> (not sure if we need it, as we don't use this field currently)

yeah, we aren't using this type but I think we should still bump this module

**Review by milosgajdos — APPROVED** [review]

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
