### PR TITLE
Restore documentation that was moved to docker docs repository

### PR DESCRIPTION
**Pull request by thaJeztah**
- Revert "Remove old documentation source, add README on migration"
    this reverts commit https://github.com/docker/distribution/commit/da8bcbb3029b79ad25cb8cb5da166e967dd3bf75
- Apply changes from docs.docker.com
    This applies changes made in the Docker documentation repository since the docs were moved there.
    Changes are taken from https://github.com/docker/docker.github.io/tree/d6fee672438a3d108c78bc23b02959955f7bc1cf/registry
- Remove code related to building docs with Hugo
    This code was outdated and no longer maintained, and mainly used to pre-flight docs changes before publishing to docs.docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
@justincormack ptal

**Review by justincormack — APPROVED** [review]

**Comment by thaJeztah** [comment]
I might try to integrate the docs from the docs repo, keeping history if I find the time

**Review by milosgajdos — CHANGES_REQUESTED** [review]
We'll need to rewrite GH repo references to the new org URL

**Comment by thaJeztah** [comment]
Ah, yes, I need to find time to restore "keeping history", and will then add a commit to rewrite the references. DCO check may be 

Not sure what the "whitespace errors" are 🤔 odd.

```
0ebe73c - FAIL - has whitespace errors. See `git show --check 0ebe73ca69548eb40b88b8dee821355129670609`.
86bf8a5 - FAIL - has whitespace errors. See `git show --check 86bf8a5e9c97c13b5a41b1e414dd8b3711d1d2ac`.
```

If I _do_ restore with git history, we may have to "skip" the DCO check, because commits from the docker documentation repository are not forced to have a DCO sign-off, so we should probably make an one-time exception for that case.

**Comment by thaJeztah** [comment]
closing in favour of https://github.com/distribution/distribution/pull/3397

**Pull request closed without merging**
