### PR TITLE
Add a storage driver for Baidu bos cloud storage

### PR DESCRIPTION
**Pull request by guoyao**

### CODE REVIEW

**Comment by dmcgowan** [comment]
@guoyao thank you for your patience during the review process. We are trying to assign an owner to help own the review process. For storage drivers we also ask the original contributor to commit to maintaining the driver or help recommend someone that will be able to maintain to. Maintaining includes looking into bugs found by other users with the driver as well as help in reviewing further changes to the driver. You will not be required to follow the issue tracker closely as we will ping you when a relevant issue or pull request is open that we want your assistance with.

To get started, do you might breaking apart the original commit into 2 commits, one with has the vendoring change and another for non-vendor changes.

**Comment by guoyao** [comment]
Hi, @dmcgowan, I have broken apart the original commit into 2 commits, and I promise I will take on the task of maintaining the driver.

**Comment by guoyao** [comment]
Hi, @dmcgowan, did you find an owner to help own the review process?

**Comment by dmcgowan** [comment]
@guoyao how much does the API differ from the S3 API? I see parts of it are copied out from the S3 driver.

**Comment by guoyao** [comment]
@dmcgowan

Baidu BOS is a cloud storage similar to AWS S3 and Aliyun OSS, so the BOS API is similar to S3, but there are still some differences, e.g. authentication details, available regions, host for bucket to access, etc.

 And currently, I provide the Baidu BOS GO API in https://github.com/guoyao/baidubce-sdk-go

**Comment by guoyao** [comment]
@dmcgowan any questions ?

Thanks!

**Comment by guoyao** [comment]
@dmcgowan 

Hope to hear from you!

Thanks!

**Comment by guoyao** [comment]
@dmcgowan any questions ?

Thanks!

**Comment by dmcgowan** [comment]
@guoyao sorry to keep you waiting. Right now we would like to avoid accepting another S3 clone driver. Trying to decide on other possible solutions to get this supported. Our resistance is related to fixes in the s3 sdk requiring duplication of fixes in each of the cloned drivers. Ideally these drivers could be supported either outside of this repository or using a base s3 driver which could share the same implementation.

**Comment by dmp42** [comment]
@guoyao does Baidu bos now work out of the box the AWS SDK?

**Comment by milosgajdos** [comment]
Hi, we won't be adding any new storage drivers to registry at this point, so I'm closing this PR.

Feel free to reopen if you disagree.

**Pull request closed without merging**
