### PR TITLE
document resource class deprecation

### PR DESCRIPTION
**Pull request by sagikazarmark**
This is a bare minimum PR for documenting resource class deprecation. Feedback welcome!

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]

**Comment by Jamstah** [comment]
Not sure I can properly review this, I have no knowledge of the auth system we're using.

If there isn't another active reviewer I'd have to dig around a little.

**Comment by milosgajdos** [comment]
There are currently 3 different types of auth supported by this project, but this change is related to authZ i.e. authorization [token scopes] for the requested resource - at the moment only repository resources are supported, the class of a resource is no longer supported by any public registry, including Docker Hub.

**Comment by jcarter3** [comment]
A bit more context here - the only "class" that was in the wild was `plugin` - and this wasn't added directly by the registry, it was added within moby (it parsed/rebuilt the scopes). This behavior was corrected/removed a while back.

**Comment by milosgajdos** [comment]
PTAL @thaJeztah

**Review by thaJeztah — APPROVED** [review]
SGTM

**Pull request merged**
