### PR TITLE
Remove waynr from MAINTAINERS

### PR DESCRIPTION
**Pull request by waynr**
Unfortunately, I don't think I am a good candidate for maintainers on this repo. I originally joined because I was tech lead on a cloud product built around distribution and wanted to help get some of our fork's changes upstream. I have since been laid off and don't intend to work on container registries in the future.

Thanks for having me and good luck with everything!

### CODE REVIEW

**Comment by milosgajdos** [comment]
Was great having you 🤝

**Review by DavidSpek — APPROVED** [review]
LGTM

**Review by SteveLasker — APPROVED** [review]
A reluctant but understanding LGTM

**Review by deleteriousEffect — APPROVED** [review]
Sorry to see you go, but LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM, and THANKS!

**Pull request merged**
