### PR TITLE
Update api.md

### PR DESCRIPTION
**Pull request by chadchristenson**
Fixed a typo.

### CODE REVIEW

**Comment by milosgajdos** [comment]
Can you please sign your commit as per the contribution guidelines?

**Comment by milosgajdos** [comment]
@chadchristenson ping

**Comment by DavidSpek** [comment]
@chadchristenson Friendly ping.

**Comment by milosgajdos** [comment]
Closing, addressed in https://github.com/distribution/distribution/pull/3998

**Pull request closed without merging**
