### PR TITLE
Update to go 1.16, and run CI on 1.15.x and 1.16.x

### PR DESCRIPTION
**Pull request by thaJeztah**
corresponding PR for the 2.7 branch is https://github.com/distribution/distribution/pull/3472

fixes https://github.com/distribution/distribution/issues/3484

### CODE REVIEW

**Comment by wy65701436** [comment]
for the main, we can update the `go.mod` as well?

**Comment by thaJeztah** [comment]
> for the main, we can update the `go.mod` as well?

It's already on go1.15, is there a reason for marking 1.15 as "not supported"?

**Comment by thaJeztah** [comment]
I suspect the repository configuration needs to be updated because the `build` is now multiple options (go1.15, go1.16);

Screenshot 2021-08-10 at 14 43 38

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by milosgajdos — APPROVED** [review]

**Comment by milosgajdos** [comment]
I think adding a build matrix may have broken mandatory status check requirements settings on this repo 🤔 
It's stuck in the yellow-ish state

**Comment by thaJeztah** [comment]
@milosgajdos yup; https://github.com/distribution/distribution/pull/3474#issuecomment-895996553. I guess someone with admin privileges needs to modify the configuration

**Comment by milosgajdos** [comment]
Oh, gotcha, @thaJeztah . I somehow missed that 🤦‍♂️ Ok, I think we need an extra job that checks that all matrix sub-jobs succeed https://github.community/t/status-check-for-a-matrix-jobs/127354

**Comment by milosgajdos** [comment]
Sadness.

@chrispat can you suggest what we can do here?

**Comment by chrispat** [comment]
The only option right now would be to update the required checks to include the new checks that are created with the matrix and remove the `build` check.  Having the ability to require a whole matrix is on our backlog.

**Comment by thaJeztah** [comment]
Thanks @chrispat  - I was looking at the page that @milosgajdos linked to, and (and reading the reference), and wondering if using `success()` instead of `always()`, combined with `needs: <something>` would work, but didn't try yet.

I guess changing the config should do the trick for now (I don't think I have the permissions to change it though); would that invalidate all existing PRs though?

**Comment by milosgajdos** [comment]
> would that invalidate all existing PRs though?

yeah, I think we'd have to re-trigger them -- but first theyd also have to be rebased 🤔

**Comment by thaJeztah** [comment]
We could temporarily remove them as "required" (assuming we don't merge on "red" anyway, and we already have other tests that are required)

**Comment by milosgajdos** [comment]
> We could temporarily remove them as "required" (assuming we don't merge on "red" anyway

Hm, we could, but I'm a bit cautious because if a build fails and someone accidentally merges, all pandas become sad somewhere. We do have `e2e` and `conformance` required checks, though so those _might_ just be find for the time being

**Comment by thaJeztah** [comment]
You don't trust people to only merge when it's green?  :trollface:

**Comment by milosgajdos** [comment]
I've disabled the requirement on `build` for the time being until GH add the option to require a whole matrix ✅

**Comment by thaJeztah** [comment]
Thanks! Looks like that worked; all ✅ now

**Pull request merged**
