### PR TITLE
Remove deprecated version field

### PR DESCRIPTION
**Pull request by tiborrr**
https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]
LGTM, just adding this link for reference to compose spec: https://github.com/compose-spec/compose-spec/blob/main/04-version-and-name.md#version-top-level-element-obsolete

**Comment by thaJeztah** [comment]
Looks like the example is still written for compose v1 (`docker-compose`), which is EOL, so probably should be updated to use `docker compose` (space instead of hyphen).

**Comment by thaJeztah** [comment]
Looks like there's a couple of other places as well;

```bash
git grep 'docker-compose[^\.-]'
docs/content/about/deploying.md:$ docker-compose up -d
docs/content/recipes/apache.md:$ docker-compose up -d
docs/content/recipes/nginx.md:$ docker-compose up -d
releases/v3.0.0-alpha.1.toml:* Use docker-compose spec v3 in nginx receipt ([#3872](https://github.com/distribution/distribution/pull/3872))
releases/v3.0.0-alpha.1.toml:  * [`c624b9ed`](https://github.com/distribution/distribution/commit/c624b9eda7d193856216ee0013468777a16f2e8a) Use docker-compose spec v3 in nginx receipt
```

**Comment by tiborrr** [comment]
@thaJeztah 

`deploying.md` is OK (no changes required)
`apache.md` is OK (no changes required)
`nginx.md` is OK (no changes required)
`v3.0.0-alpha.1.toml` does not require updating as this shows changes that have been in the past and I do not think this requires updating.

@milosgajdos `nginx.md` does not have a version field in the example

This patch can be merged as far as I am concerned.

**Comment by tiborrr** [comment]
@thaJeztah can you approve this change with the changes I have made?

**Review by thaJeztah — APPROVED** [review]
oh! thought I did

LGTM, thanks!

**Pull request merged**
