### PR TITLE
[WIP] Support mixed mirror registry

### PR DESCRIPTION
**Pull request by wzshiming**
Enable writing to local storage with mirror registry

### CODE REVIEW

**Comment by milosgajdos** [comment]
Can you explain what is it you are trying to achieve with this PR?

**Comment by wzshiming** [comment]
I want to enable both the local storage registry and the mirror registry,
The mirror registry alone will work, but I want to be able to actively synchronize some mirrors in advance when the number of mirrors is high.

**Comment by liyimeng** [comment]
@wzshiming This sounds good idea! how far have you gone?

**Comment by wzshiming** [comment]
I'm currently doing this in a different way, starting two registries, one using mirrors as an external service and the other as an internal service using active sync writes

**Comment by wzshiming** [comment]
I'm currently doing this in a different way, starting two registries, one using mirrors as an external service and the other as an internal service using active sync writes

**Comment by liyimeng** [comment]
I just realize this might not necessary. If we wanna cache an image, we can pull it behind the registry and let it cached in advanced.

**Comment by wzshiming** [comment]
Yes, this does work if you don't need to check what has been synced.

**Comment by wzshiming** [comment]
Hi @milosgajdos @liyimeng

I did this in a different way, I implemented a generic container image proxy.

https://github.com/wzshiming/crproxy

**Comment by wzshiming** [comment]
Already reached in other ways

**Pull request closed without merging**
