### PR TITLE
docs: remove README.md that point to Docker's repo

### PR DESCRIPTION
**Pull request by liubin**
It seems the repo name of `docker.github.io` has been renamed to `docs`

### CODE REVIEW

**Comment by thaJeztah** [comment]
Oh! I think this file must be deleted; this was added when the docs were moved out (https://github.com/distribution/distribution/pull/1985), but they were moved back in through this PR;

- https://github.com/distribution/distribution/pull/3397

**Review by thaJeztah — CHANGES_REQUESTED** [review]
(see my comment)

the TL;DR was that the docs were moved to the central "docs" repository when it was one of Docker's open source projects, but the project has been donated to the CNCF since. That means that docker's documentation _may_ have some documentation, but this repository should be considered the canonical for documentation of the project itself.

**Comment by liubin** [comment]
Thank your explain, @thaJeztah, updated.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

@milosgajdos PTAL

**Pull request merged**
