### PR TITLE
Storage Driver for Kingsoft Cloud KS3

### PR DESCRIPTION
**Pull request by softlns**
This driver implements the storagedriver.StorageDriver interface and uses Kingsoft Cloud KS3 Open Storage Service as storage backend.

The documentation for this driver is in https://github.com/softlns/distribution/blob/master/docs/storage-drivers/ks3.md

To run the unit test case for this driver, you need set the following environment variables before

```
export KS3_ACCESS_KEY=<YOUR_ACCESS_KEY>
export KS3_SECRET_KEY=<YOUR_SECRET_KEY>
export KS3_REGION=<KS3_REGION_CODE>   E.g. ks3-us-west-1
export KS3_BUCKET=<KS3_BUCKET_NAME>
export KS3_ENCRYPT=false
export KS3_SECURE=false
```

NOTE: This driver reuses the code logic from the S3 driver.

Signed-off-by: Lain (softliunaisen@gmail.com)

### CODE REVIEW

**Comment by RichardScothern** [comment]
thank you for the contribution @softlns  

Someone will take a look at this driver.   In the meantime, can you provide a link to the KS3 storage documentation? Thanks!

**Comment by softlns** [comment]
@RichardScothern 
 http://ks3.ksyun.com/doc/api/index.html is the link to the KS3 storage documentation which is written in Chinese. In addition,  KS3 API is similar to S3, but there are still some differences, e.g. Authentication, Region definition, host for Bucket to access, etc. 

And currently, I provide the Kingsoft KS3 GO API in https://github.com/softlns/ks3-sdk-go which refers the S3 API of https://github.com/AdRoll/goamz. 

Thanks!

**Comment by RichardScothern** [comment]
thanks @softlns 

Given the closeness of the S3 and KS3 interfaces, do you think it's possible to implement this driver using the existing S3 driver?

We are going to remove the the S3 driver which is based upon  https://github.com/AdRoll/goamz because the `s3-aws` driver which is based on the official Amazon SDK is more efficient and better supported.

**Comment by softlns** [comment]
@RichardScothern 

In the beginning, we have tried using the existins S3 driver directly. Unfortunately, failed. 
Due the differences between the S3 and KS3 interfaces, we can't implement KS3 storage driver based on the official Amazon SDK.

Actually, we have already used it in several internal projects in Kingsoft Cloud inc. It is pretty solid now.
Along with the iteration of the project, we will continue to maintain the KS3 storage driver and the [ks3-sdk-go](https://github.com/softlns/ks3-sdk-go).

Thanks!

**Comment by softlns** [comment]
@RichardScothern

Hi, has someone completed the review job yet?

Thanks!

**Comment by stevvooe** [comment]
Any reason this can't use the s3 driver?

**Comment by dmp42** [comment]
@softlns are you still interested in working on this?

**Comment by milosgajdos** [comment]
We are not accepting any new storage drivers at the moment. Plus this PR is wildly outdated. Please reopen if you insist.

**Pull request closed without merging**
