### PR TITLE
Update to xx 1.1.1

### PR DESCRIPTION
**Pull request by crazy-max**
https://github.com/tonistiigi/xx/releases/tag/v1.1.1

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

@crazy-max do you know if there will be a v1.1.2 with my fix for macOS? https://github.com/tonistiigi/xx/compare/v1.1.1...master

**Comment by crazy-max** [comment]
> LGTM
> 
> @crazy-max do you know if there will be a v1.1.2 with my fix for macOS? [tonistiigi/xx@v1.1.1...master](https://github.com/tonistiigi/xx/compare/v1.1.1...master)

Ah good point, forgot to trigger a release for it. Will do!

**Comment by milosgajdos** [comment]
@crazy-max should I wait for the new release instead of merging this?

**Comment by crazy-max** [comment]
@milosgajdos No good to go, it's unrelated with this repo.

**Comment by thaJeztah** [comment]
> Ah good point, forgot to trigger a release for it. Will do!

thanks! didn't want to push too hard for it, as it was fixing a bit of a corner-case, but thought I'd check 😅

**Comment by crazy-max** [comment]
@thaJeztah Btw https://github.com/distribution/distribution/pull/3644 LGTY or does it need some changes?

**Pull request merged**
