### PR TITLE
Prepare for v2.7.2 release

### PR DESCRIPTION
**Pull request by milosgajdos**
This PR contains short release notes and version bump for `2.7.2` patch release.

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by heww — APPROVED** [review]

**Review by joaodrp — APPROVED** [review]

**Comment by defensivedepth** [comment]
Is there a target date for this release?

**Comment by antoinetran** [comment]
Hi, same question as @defensivedepth , could we have a roadmap please? The 2.7.1 more than one year old ^^ Thanks.

**Review by justincormack — APPROVED** [review]

**Comment by milosgajdos** [comment]
Closing in favor of https://github.com/distribution/distribution/pull/3552

**Pull request closed without merging**
