### PR TITLE
Add some secure compilation options, especially PIE and RELRO.

### PR DESCRIPTION
**Pull request by TaylorKanper**
As the title says.

Closes: https://github.com/distribution/distribution/issues/3617

### CODE REVIEW

**Review by milosgajdos — COMMENTED** [review]
Strange, the title mentioned PIE, but I see no reference of it in the PR. Am I missing something?

**Comment by TaylorKanper** [comment]
> 



> Strange, the title mentioned PIE, but I see no reference of it in the PR. Am I missing something?

yes, you are right, I missing some code, Thank you very much.

**Comment by milosgajdos** [comment]
You need to sign your commit

**Comment by TaylorKanper** [comment]
> You need to sign your commit

ok

**Review by milosgajdos — APPROVED** [review]

**Review by milosgajdos — APPROVED** [review]

**Comment by milosgajdos** [comment]
CC: @thaJeztah @deleteriousEffect @wy65701436

**Review by DavidSpek — APPROVED** [review]
LGTM! @milosgajdos This can be merged now.

**Pull request merged**
