### PR TITLE
Fix html not rendering markdown link properly

### PR DESCRIPTION
**Pull request by khaosdoctor**
Related to #3408

### CODE REVIEW

**Comment by khaosdoctor** [comment]
Yay!

**Comment by milosgajdos** [comment]
Thanks. Personally, I think we need to look into docs generator, rather than mixing HTML with/into markdown. I'm not entirely sure how the docs are generated.

if you meant to address the issues on the Docker run docs, though, you might wanna open a PR [here](https://github.com/docker/docker.github.io). There is a compose file that lets you render the pages etc.

**Comment by milosgajdos** [comment]
So I had a look at this again I wonder if the problem is that the original file had a `markdown` link mixed into `HTML` and thus failed to be rendered by GH properly. I might be wrong, though so I'll let others comment here.

**Review by milosgajdos — APPROVED** [review]

**Comment by khaosdoctor** [comment]
> So I had a look at this again I wonder if the problem is that the original file had a `markdown` link mixed into `HTML` and thus failed to be rendered by GH properly. I might be wrong, though so I'll let others comment here.

What do you mean? Can you point out where this is happening, I might be able to help :)

**Comment by milosgajdos** [comment]
I mean the original content (before your fix):
```
...
...
    <dd>
...
...        
[RFC6749 Appendix A.1](https://tools.ietf.org/html/rfc6749#appendix-A.1).
    </dd>
...
...
```

The above "mixes" `HTML` and `markdown` syntax (`dd` HTML tag + markdown URL) syntax). So I'm wondering with GitHub flavored markdown somehow doesn't handle that well. Mind you, I've no expertise in markup languages and/or their specs :)

**Comment by khaosdoctor** [comment]
The weird thing is that the preview pane shows it right, for some reason.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
