### PR TITLE
Cleanup storage cache metrics

### PR DESCRIPTION
**Pull request by SuperQ**
Split request and hit metrics into separate metrics, rather than using
labels. This avoids duplication of data and makes metric math easier.

* Count cache errors separately to avoid weird math.
* Hit ratio: `registry_storage_cache_hits_total / registry_storage_cache_requests_total`
* Miss ratio: `1 - (registry_storage_cache_hits_total / registry_storage_cache_requests_total`
* Misses: `registry_storage_cache_requests_total -
registry_storage_cache_hits_total`

### CODE REVIEW

**Comment by SuperQ** [comment]
@manishtomar, can you also look at this one?

**Comment by milosgajdos** [comment]
@SuperQ would you mind rebasing? Feel free to close if you no longer want to work on this.

**Comment by SuperQ** [comment]
@milosgajdos rebase done. Updated to also split out the errors into a separate metric. Things get weird when you have to figure out hits/misses/errors that way.

I wonder if it would be a good idea to migrate away from the `docker/go-metrics` wrapper package. It seems abandoned.

**Comment by milosgajdos** [comment]
@SuperQ that's a good question. Normally I'd say why not, but do we have any extra requirements that are not met by that module? I dont think we do

**Comment by SuperQ** [comment]
I don't think the wrapper library adds much value.

**Review by deleteriousEffect — APPROVED** [review]
These look like solid changes to me :rocket:

**Review by milosgajdos — APPROVED** [review]

**Pull request merged**
