### PR TITLE
Add dualstack option to S3 storage driver

### LINKED ISSUE #3067: s3 Storage Driver Does Not Use Dualstack
The s3 storage driver does not use the `UseDualStack` AWS SDK option, which allows the client to communicate with AWS S3 over IPv6 as well as IPv4 [1]. This option is required if the registry is deployed in an IPv6-only network.

[1] https://docs.aws.amazon.com/AmazonS3/latest/dev/dual-stack-endpoints.html#dual-stack-endpoints-sdks

### PR DESCRIPTION
**Pull request by adambkaplan**
Allow the storage driver to optionally use AWS SDK's dualstack mode.
This allows the registry to communicate with S3 in IPv6 environments.
Fixes #3067

Signed-off-by: Adam Kaplan <adam.kaplan@redhat.com>

### CODE REVIEW

**Comment by adambkaplan** [comment]
fyi @dmage

**Comment by adambkaplan** [comment]
Bump @justincormack @dmcgowan.

We have been running this code in production for OpenShift's internal registry for almost two years now. It enables support for S3 storage on dualstack/IPv6.

**Comment by justincormack** [comment]
The AWS docs say the UseDualStack option is deprecated and you should use UseDualStackEndpoint https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config.WithUseDualStack

**Comment by milosgajdos** [comment]
Hey @adambkaplan can you please rebase so that GH Action CI gets triggered -- this PR has remnants of the previous CI setup.

**Comment by adambkaplan** [comment]
@justincormack updated to use the new DualStack configuration option. Note that this required a dependency bump (which I put in a separate commit).

@milosgajdos rebased to trigger the new GH Actions.

**Review by milosgajdos — APPROVED** [review]

**Review by justincormack — APPROVED** [review]

**Pull request merged**
