### PR TITLE
[release/2.8] feat: Add HTTP2 for unencrypted HTTP (v2)

### PR DESCRIPTION
**Pull request by erezrokah**
Replaces https://github.com/distribution/distribution/pull/4242

Also adds this feature behind an opt-in option to make it non breaking (I don't think it should break things but could be considered a breaking change in the default behavior)

Fixes https://github.com/distribution/distribution/issues/4241

You can test via:

```
docker build . -t registry:v2-h2c
docker run -e REGISTRY_HTTP_H2C_ENABLED='true' -p 5000:5000 registry:v2-h2c
```

Then on a separate shell:

```
curl -i --http2-prior-knowledge http://localhost:5000 
HTTP/2 200 
cache-control: no-cache
content-length: 0
date: Fri, 05 Jan 2024 15:40:04 GMT

curl -i http://localhost:5000
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Fri, 05 Jan 2024 15:40:31 GMT
Content-Length: 0
```

### CODE REVIEW

**Comment by erezrokah** [comment]
If you're OK with this change for v2 I can port it to v3 as well

**Comment by milosgajdos** [comment]
I think adding this to v3 would be nice 🤔

**Review by milosgajdos — COMMENTED** [review]
@thaJeztah there is something sad happening and I have a feeling it might have to do with the old vendorinig

**Comment by erezrokah** [comment]
> I think adding this to v3 would be nice 🤔

PR for v3 https://github.com/distribution/distribution/pull/4248. I used the existing option since v3 is already a major version bump so this way the defaults for TLS and non TLS will be the same

**Review by thaJeztah — CHANGES_REQUESTED** [review]
I don't think we should add new features to v2. It's in maintenance mode, so only bug-fixes and security-fixes should go in; other changes should go into v3

**Comment by milosgajdos** [comment]
> I don't think we should add new features to v2. It's in maintenance mode, so only bug-fixes and security-fixes should go in

Yeah, we shouldn't be accepting this to v2

**Comment by wy65701436** [comment]
I am against and we should consider adding this into main.

**Comment by erezrokah** [comment]
> I don't think we should add new features to v2. It's in maintenance mode, so only bug-fixes and security-fixes should go in; other changes should go into v3

👍 I wasn't sure what's the timeline for the v3 release. I'll go ahead and close this PR

**Pull request closed without merging**
