### PR TITLE
feat!: remove schema1 from registry handlers

### PR DESCRIPTION
**Pull request by DavidSpek**
Part of: https://github.com/distribution/distribution/issues/3966

This PR is a step towards the elimination of `schema v1` support in `distribution`.

This PR removes schema1 package references from the `registry/handlers` package.

### CODE REVIEW

**Comment by milosgajdos** [comment]
I have a fix for these tests but even though I'm a maintainer I can't push them to your fork which makes me think you might have some tighter permissions set up on your forked repo 🤷‍♂️

**Comment by DavidSpek** [comment]
@milosgajdos Seems to be because I created the PR from an organization fork and that setting isn’t available for org owned forks. Feel free to just create a new PR and we can close this one.

**Comment by milosgajdos** [comment]
> @milosgajdos Seems to be because I created the PR from an organization fork and that setting isn’t available for org owned forks. Feel free to just create a new PR and we can close this one.

Aaah, that makes a lot of sense! Ok, will open a separate PR then. Let's keep this open till then

**Comment by DavidSpek** [comment]
Closing in favor of https://github.com/distribution/distribution/pull/3987

**Pull request closed without merging**
