### PR TITLE
reference: implement Sort()

### PR DESCRIPTION
**Pull request by thaJeztah**
This forward-ports the following patches;

- https://github.com/containerd/containerd/pull/5250
- https://github.com/containerd/containerd/pull/6993
- https://github.com/containerd/containerd/pull/7007

Patches were slightly modified to account for different import paths.

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]

**Comment by brackendawson** [comment]
Should Sort() have a Fuzzer for oss-fuzz to test?

**Comment by thaJeztah** [comment]
Perhaps 🤔 that said, there's no fuzzers currently running on this package in containerd (where this comes from). Perhaps it would be good to add them once (_IF_ depends in wether the maintainers accept that) this package is moved to a separate module; see https://github.com/distribution/distribution/issues/3587#issuecomment-1307396507

**Comment by brackendawson** [comment]
That sounds like a good plan, it also means you don't need to worry about whatever #3780 does to the fuzzers in this repo.

**Comment by thaJeztah** [comment]
> WDYT about squashing this PR down to one commit with a description like "reference: implement Sort()"

Yes, works for me; I had my branch squashed locally, then last minute wasn't sure wether or not I should squash, or to try to keep contributor history, but I guess it's ok to squash. I could include a link to the original implementation in the commit message.

**Review by corhere — APPROVED** [review]

**Pull request merged**
