### PR TITLE
Dockerfile: fix filenames of artifacts

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@milosgajdos @corhere @squizzi ptal 🤗

**Review by milosgajdos — APPROVED** [review]

**Review by corhere — APPROVED** [review]
Obviously it's a tarball of a tarball, gzipped /s 😁

**Comment by thaJeztah** [comment]
Yeah, I highly suspect this was a copy/pasta from a release-pipeline of another repo that chose to use `.tgz` instead of `.tar.gz`. Either one is fine, but not "both" 😂

**Comment by thaJeztah** [comment]
But the unfortunate (or perhaps _fortunate_) result was that the release uploaded only the `.sha256` checksums, and not the actual binaries;

Screenshot 2023-05-10 at 00 35 25

**Pull request merged**
