### PR TITLE
add double newlines in ADOPTERS.md

### PR DESCRIPTION
**Pull request by drornir**
Using double newlines in markdown makes it easier to read in markdown readers, e.g github

### CODE REVIEW

**Review by deleteriousEffect — APPROVED** [review]

**Comment by deleteriousEffect** [comment]
Thanks @drornir this LGTM.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by wy65701436** [comment]
@drornir could you please fix the DCO?

**Comment by drornir** [comment]
Yes I'm just a bit busy but I'll get around to it this weekend

**Comment by milosgajdos** [comment]
ping @drornir

**Comment by drornir** [comment]
Thanks for the patience!

**Pull request merged**
