### PR TITLE
Delete reference package

### LINKED ISSUE #4123: remove reference package from distribution
We should point the users to https://github.com/distribution/reference

### PR DESCRIPTION
**Pull request by corhere**
- Fixes #4123 

Users should import it from its new location github.com/distribution/reference.

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]

**Comment by milosgajdos** [comment]
PTAL @Jamstah

**Review by Jamstah — APPROVED** [review]

**Comment by Jamstah** [comment]
Although @thaJeztah wasn't in the meeting where we decided to do this, I feel he deserves a heads up :)

**Comment by thaJeztah** [comment]
Ah, yes, we backported the deprecation in https://github.com/distribution/distribution/pull/4063, so people should get the message if they're using the released versions, so I think this is fine.

We should do a v2.8.4 release though to fix my rather unfortunate slip-up (https://github.com/distribution/distribution/pull/4114) 🙈 😭

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
