### PR TITLE
Fix gcs storage driver

### PR DESCRIPTION
**Pull request by flavianmissi**
Based on https://github.com/distribution/distribution/pull/3702.

Also fixes the OSS `Cancel` method which was missing a context parameter.

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]
I'm LGTM-ing this as it's a port of https://github.com/distribution/distribution/pull/3702

I dont want this to be blocked for another year by unproductive conversations - we should look for perfection by iterating before v3 is released.

**Comment by flavianmissi** [comment]
Who can help with the 2nd approval @milosgajdos ?

**Comment by milosgajdos** [comment]
CC: @distribution/maintainers

**Comment by flavianmissi** [comment]
bumping this as it's still pending a review.

**Review by squizzi — APPROVED** [review]
Based on the discussion in #3702 and the approvals there as well as the minor additional commits added in this to add context to `Cancel` and bump some gcs dependencies; I feel this is safe to approve.

**Comment by dkulchinsky** [comment]
great to see this getting merged! thanks to all for driving this effort 👏🏼

**Comment by milosgajdos** [comment]
Big thanks go to @jmontleon for the initial effort and @flavianmissi for getting it across the finish line 🙇

**Pull request merged**
