### PR TITLE
Add tests for tags list pagination

### PR DESCRIPTION
**Pull request by joaodrp**
Adds test coverage for https://github.com/distribution/distribution/pull/3143.

### CODE REVIEW

**Comment by joaodrp** [comment]
cc @eyJhb

**Review by milosgajdos — APPROVED** [review]
LGTM.

This kinda made me wonder if all those `URLBuilder` methods should provide variadic `url.Value` params in `v3`.

Yes I understand that would mean breaking `notifications.URLBuilder`, but since we've decided to break some interface in `v3` we might as well do this.

**Comment by joaodrp** [comment]
> LGTM.
> 
> This kinda made me wonder if all those `URLBuilder` methods should provide variadic `url.Value` params in `v3`.
> 
> Yes I understand that would mean breaking `notifications.URLBuilder`, but since we've decided to break some interface in `v3` we might as well do this.

That's a good point. However, do we have a use case (now or planned for the near future) for URL values in other methods that don't have one already? Exposing these before they're needed is counter-intuitive IMO.

**Comment by milosgajdos** [comment]
We don't actually, no. I was merely thinking out loud just in case the topic comes up.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
