### PR TITLE
[cherry pick] Automated cherry pick of #4047 origin release 2.8

### PR DESCRIPTION
**Pull request by dimitar-kostadinov**
Cherry pick PR #4047 to release/2.8 branch.

### CODE REVIEW

**Comment by ialidzhikov** [comment]
@milosgajdos, @Jamstah can you have a look? Thanks in advance!

**Comment by milosgajdos** [comment]
We're not planning another 2.8 release anytime soon. We'd like to get a v3 alpha out soon.

A bunch of America folks are out for thanksgiving hols (+ the runup to it) so we'll wait until the milestone PRs are cleared and then charge on

**Comment by ialidzhikov** [comment]
Hi Milos,

Thank you for providing the details.

From our side, we ([Gardener project](https://gardener.cloud/)) are looking forward to consume a new release of distribution/distribution to adopt the following upstream changes:
- Configurable proxy TTL (https://github.com/distribution/distribution/pull/3880). There is also open backport PR to the release/2.8 branch: https://github.com/distribution/distribution/pull/4090
- Proxy metrics fix and metrics in prometheus format: https://github.com/distribution/distribution/pull/4045 and https://github.com/distribution/distribution/pull/4047

Is it possible to provide a rough estimation when a new major/minor release could happen? The last minor release (v2.8.0) was cut on Feb 7, 2022, more than year and a half ago. I am concerned about the timelines for v3.0.0 as in the release milestone there are issues that are open since 2018. Would you consider cutting a new minor release v2.9.0 instead? 
Thanks in advance!

**Comment by milosgajdos** [comment]
We are aiming to cut an alpha/beta before the EOY.

We still need to investigate the following issues before we cut the release:
* https://github.com/distribution/distribution/issues/2668
* https://github.com/distribution/distribution/issues/2670

TBD

**Comment by thaJeztah** [comment]
It looks like this is backporting new functionality, which is out of scope for a 2.8 patch release as well.

**Comment by ialidzhikov** [comment]
@milosgajdos @thaJeztah any news with the new release? When we can expect a new release (that is not alpha/beta) to consume?

**Comment by milosgajdos** [comment]
A stable release is a bit far away, but alpha release is baking. 

We've hit a snug. See this discussion: https://github.com/distribution/distribution/pull/4185#discussion_r1419482745

Once we've resolved that issue, we'll cut the alpha release.

**Comment by ialidzhikov** [comment]
> Once we've resolved that issue, we'll cut the alpha release.

I see that the corresponding PR (https://github.com/distribution/distribution/pull/4185). Could you cut the new release? Thanks in advance!

**Comment by milosgajdos** [comment]
We cut a new release last night, @ialidzhikov  https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1 out I'm inclined to close this PR as it won't be merged into `2.x` branch. All the further development is going into getting a stable `v3` release out next year.

**Comment by milosgajdos** [comment]
With https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1 out, I'd suggest closing this PR as we won't be adding anything into the `v2.x` branch which will be deprecated very soon.

**Comment by ialidzhikov** [comment]
@milosgajdos thank you for the efforts for the v3.0.0-alpha.1. We will experiment with it and provide feedback.
However, we are looking forward to v3.0.0 - we cannot rollout alpha/beta/non-GA versions in our environements.

**Comment by ialidzhikov** [comment]
Hi @milosgajdos ,

When can we expect v3.0.0? Thanks in advance!

**Comment by ialidzhikov** [comment]
> We will experiment with it and provide feedback.

Just to provide the feedback that I provided in Slack:
> It (3.0.0-alpha.1) is working for us. Our e2e tests are passing. We even plan to consume it in our prod envs - ref https://github.com/gardener/gardener-extension-registry-cache/pull/138.
Except the minor nit in https://github.com/distribution/distribution/issues/4270. But there is a workaround for it.

**Pull request closed without merging**
