### PR TITLE
Proxy cache configurable

### PR DESCRIPTION
**Pull request by Mattes83**
This is a follow up of #3238

### CODE REVIEW

**Comment by Mattes83** [comment]
@milosgajdos I opened this PR because of your comment in https://github.com/distribution/distribution/issues/1994#issuecomment-1050660883
What do you think?

**Comment by milosgajdos** [comment]
There is a failing test CI action here mm

**Comment by milosgajdos** [comment]
This is failing to build

**Comment by milosgajdos** [comment]
@AnnaGuzy there is a merge conflict. Besides, the CI never passed. @Mattes83 do you wanna look into this?

**Comment by milosgajdos** [comment]
Can we close this as this was merged https://github.com/distribution/distribution/pull/3880 ?

**Pull request closed without merging**
