### PR TITLE
OCI: POST request with digest and blob should yield 201

### PR DESCRIPTION
**Pull request by waynr**
fixes https://github.com/docker/distribution/issues/3230 OCI Conformance: POST request with digest and blob should yield a 201

This addresses a couple compliance failures mentioned in #3203 by adding a new function, `PostBlobData`, that dispatches to different handler functions depending on the contents of the `digest` query parameter and whether or not the POST request has a non-zero content length.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Is it guaranteed that processing is complete (irregardless of the storage backend?) I have a feeling that both 202 and 201 can be valid responses.



@dmcgowan @manishtomar PTAL

**Comment by waynr** [comment]
@thaJeztah the [spec](https://github.com/opencontainers/distribution-spec/blob/master/spec.md#initiate-monolithic-blob-upload) says:

> Initiate a resumable blob upload. If successful, an upload location will be provided to complete the upload. Optionally, if the digest parameter is present, the request body will be used to complete the upload in a single request.

and

> Upload a blob identified by the digest parameter in single request. This upload will not be resumable unless a recoverable error is returned.

Although now that I take another look at the spec, I'm not quite sure how I came up with the requirement in code that `Content-Length` be greater than zero.

**Comment by wy65701436** [comment]
as the spec was changed per https://github.com/opencontainers/distribution-spec/pull/206, this pull-request is not valid.

**Comment by thaJeztah** [comment]
Good catch; looks like this is the updated description (if I'm reading the correct section);

> The response to a successful mount MUST be `201 Created`, and MUST contain the following header:
...
> Alternatively, if a registry does not support cross-repository mounting or is unable to mount the requested blob,
> it SHOULD return a `202`. This indicates that the upload session has begun and that the client MAY proceed with the upload.

**Comment by thaJeztah** [comment]
Looks like we can close this one indeed (also see https://github.com/distribution/distribution/issues/3230#issuecomment-1302355720)

Thanks @waynr !

**Pull request closed without merging**
