### PR TITLE
Clarify repo name regex intention

### PR DESCRIPTION
**Pull request by davidwarshaw**
Add context to comment to explain the repo name regex in addition to describing it.

Signed-off-by: David Warshaw <david.warshaw@gmail.com>

### CODE REVIEW

**Comment by dmcgowan** [comment]
Rather than just linking to the issue, you can include the reasoning in the original PR. The original reasons seem pretty straightfoward.

```
In order to support valid hostnames as name components, supporting repeated dash was added.
Additionally double underscore is now allowed as a separator to loosen the restriction for previously supported names.
```

**Comment by davidwarshaw** [comment]
Your prerogative. The key thing for me, is letting readers know this was [carefully considered](https://en.wikipedia.org/wiki/Saint_Petersburg%E2%80%93Moscow_railway#The_ruler_legend) and not a mistake.

**Comment by davidwarshaw** [comment]
bumping

**Comment by davidwarshaw** [comment]
@dmcgowan Let's get this off the board.

**Review by milosgajdos — APPROVED** [review]

**Review by joaodrp — APPROVED** [review]

**Pull request merged**
