### PR TITLE
Remove duplicate code of conduct

### PR DESCRIPTION
**Pull request by dmcgowan**
Fill in the code of conduct rather than linking to CNCF code of conduct to list available escalation points related to this project.

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]

**Comment by dmcgowan** [comment]
Maybe this PR doesn't make sense anymore since the project is under CNCF now. Linking prevents the code of conduct from becoming out of date

**Comment by milosgajdos** [comment]
This is maybe a question for @caniszczyk, but I noticed Prometheus and some other CNCF projects do link to CNCF [CoC](https://github.com/prometheus/prometheus/blob/main/CODE_OF_CONDUCT.md) in their source tree.

**Comment by dmcgowan** [comment]
Actually, Justin already added a different version in the root https://github.com/distribution/distribution/commit/67c504de8b42a62ee2855d939c48a076c7f54770#diff-a82fe1c8cecf4df558b8f06a146f9857d7706e9dbda4df8b84a559c857255332

I'll update this one just to just remove this duplicate

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
