### PR TITLE
Support OCI Artifact Manifests

### PR DESCRIPTION
**Pull request by brackendawson**
This implements support for OCI Artifact Manifests as described in the OCI 1.1 release candidate specification.

This does not add support for the new subject field in OCI Image Manifests, but it does lay common groundwork to make that a trivial change. This does not implement the referrers list API but does create the links files required to do so. This does not implement any GC. I would like to add those in subsequent pull requests to aid reviewability.

Adresses distribution/distribution#3716

This pull request is loosely based on work in https://github.com/oci-playground/distribution by:
Co-authored-by: Sajay Antony <sajaya@microsoft.com>
Co-authored-by: Tejaswini Duggaraju <naduggar@microsoft.com>
Co-authored-by: Akash Singhal <akashsinghal@microsoft.com>
Co-authored-by: Aviral Takkar <avtakkar@microsoft.com>
Co-authored-by: Julus Liu <juliusl@microsoft.com>
Co-authored-by: Josh Dolitsky <josh@dolit.ski>
Co-authored-by: Shiwei Zhang <shizh@microsoft.com>
Co-authored-by: Brandon Mitchell <git@bmitch.net>

### CODE REVIEW

**Review by milosgajdos — COMMENTED** [review]
We need to put this on hold until https://github.com/opencontainers/image-spec/pull/999 is resolved

**Comment by SamirPS** [comment]
Hello @milosgajdos @brackendawson 

Will this PR permit attaching some artefact to an OCI image on DockerHub with tools like oras attach, for example?

**Comment by milosgajdos** [comment]
We are waiting for the OCI specification to be released. There is an ongoing discussion about OCI manifest support and a few other parts of the spec might likely get updated too. Until that happens I don't expect any major registry to support any of the new capabilities.

**Comment by milosgajdos** [comment]
FYI: RC-3 of `image-spec` has been cut: https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc3

**Comment by SamirPS** [comment]
Thanks for the information

**Comment by thaJeztah** [comment]
> FYI: RC-3 of `image-spec` has been cut: https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc3

Ah yes, opened a draft PR to update it (wasn't sure if we wanted pre-releases to be in use, but can move it out of draft if we're okay with that);

- https://github.com/distribution/distribution/pull/3889

**Comment by brackendawson** [comment]
The "OCI Artifact Manifest" has been dropped from the spec and the `artifactType` field plus some additional logic added to the "OCI Image Manifest". I'm going to close this PR and implement the latest behaviour in #3834

**Pull request closed without merging**
