### PR TITLE
Fix OCI conformance workflow report and README badge

### PR DESCRIPTION
**Pull request by milosgajdos**
Signed-off-by: Milos Gajdos <milosgajdos83@gmail.com>

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by wy65701436** [comment]
We should temp set conformance pipeline non-required.

**Comment by milosgajdos** [comment]
@chrispat do you happen to know why are so many of these checks marked as Required when the GH merge settings for `main` branch only specify 2 or 3 of these?

**Comment by joaodrp** [comment]
@milosgajdos, looking at the print you shared, I see `run` in the required status checks.

Screen Shot 2021-06-29 at 10 23 27 PM

Maybe that's the reason why it's marked as required? If so, it might be enough to just give the job a different name [here](https://github.com/distribution/distribution/blob/ad8f5caba068b2d4b83ba5a1c3e9d74e1da2c16e/.github/workflows/conformance.yml#L8).

**Comment by milosgajdos** [comment]
Gotcha! So it's the workflow job checks, not the actual workflow [names]. Makes sense.

I've opened a PR to make the job names unique across workflows https://github.com/distribution/distribution/pull/3448

I've also temporarily disabled some requirements so we can merge this in and re-enable the rest of the workflow checks.

**Comment by milosgajdos** [comment]
Alright, we're back in business

**Review by joaodrp — APPROVED** [review]

**Pull request merged**
