### PR TITLE
[release/2.7]fix go check issues

### PR DESCRIPTION
**Pull request by wy65701436**
G404: Replace math rand with crypto rand

Signed-off-by: Wang Yan <wangyan@vmware.com>

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]

**Comment by thaJeztah** [comment]
should we enable `gosec` in the golangci-lint config? https://github.com/distribution/distribution/blob/main/.golangci.yml#L2

**Comment by milosgajdos** [comment]
> should we enable `gosec` in the golangci-lint config? https://github.com/distribution/distribution/blob/main/.golangci.yml#L2

I think that's a good idea, but hmm, I wonder what can of worms will that open 😅

**Comment by milosgajdos** [comment]
As a follow up to this, it seems to be be more of a [recommendation](https://go-review.googlesource.com/c/go/+/12900/), but having checked some perf benchmarks comparisons between the two methods, I think we should merge this in without much worry.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
