### PR TITLE
Add secure compilation options.

### PR DESCRIPTION
**Pull request by TaylorKanper**
Add secure compilation options.

Signed-off-by: TaylorKanper <tony_kanper@hotmail.com>

### CODE REVIEW

**Comment by TaylorKanper** [comment]
The DCO of the previous pull request is incorrect. Delete the pull request.

**Review by milosgajdos — COMMENTED** [review]
This looks good to me, but I'm not sure we'll be accepting anything into `2.8` release. I just wanted to set the expectations right on this PR.

**Comment by thaJeztah** [comment]
Is there a corresponding PR for the main branch? If we change this, at least it should be done in main first / as well

**Comment by TaylorKanper** [comment]
> Is there a corresponding PR for the main branch? If we change this, at least it should be done in main first / as well

ok,I'll submit a pull request to the main branch.

**Comment by DavidSpek** [comment]
Closing this as it won't get merged and https://github.com/distribution/distribution/pull/3623 targets the proper branch.

**Pull request closed without merging**
