### PR TITLE
 replace ListObjectsV2 with HeadObject to speed up Stat

### PR DESCRIPTION
**Pull request by DHmc133**
replace listObject usr HeadObject can accelerate image push

### CODE REVIEW

**Comment by milosgajdos** [comment]
@DHmc133 can you please
1. Describe what you are trying to achieve and the motivations behind the PR
2. Always sign your commit

Looks like there is a conflict that needs resolving

**Comment by DHmc133** [comment]
> @DHmc133 can you please
> 
> 1. Describe what you are trying to achieve and the motivations behind the PR
> 2. Always sign your commit
> 
> Looks like there is a conflict that needs resolving

We found that the listObject request will list the full amount of data to find the corresponding key, and the HeadObject can directly get the key's attributes;
Generally speaking, in large image scenarios, it can effectively improve the speed of image push.

**Review by OKEAMAH — APPROVED** [review]
Uj

**Comment by squizzi** [comment]
@DHmc133  please update your commit as well... `Update s3.go` isn't a good commit message, please follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) spec as well when writing your commit.  Perhaps something like:

```
perf: replace ListObjectsV2 with HeadObject to speed up Stat
```

**Review by OKEAMAH — COMMENTED** [review]
Cool

**Comment by milosgajdos** [comment]
this needs a rebase @DHmc133 and commit signature

**Review by DHmc133 — COMMENTED** [review]
.

**Comment by milosgajdos** [comment]
This broke the build now. And it's still missing the commit signature.

**Pull request closed without merging**
