### PR TITLE
Update api.md

### PR DESCRIPTION
**Pull request by pdevine**

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]

**Comment by milosgajdos** [comment]
@pdevine please sign your commit

**Review by deleteriousEffect — APPROVED** [review]
@pdevine thanks for the PR. I'll go ahead and approve, but I'd like to see a more descriptive title, such as `fix typo in api.md`.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by wy65701436** [comment]
@pdevine could you please fix the DCO checking?

**Comment by milosgajdos** [comment]
Closing, addressed in https://github.com/distribution/distribution/pull/3998

**Pull request closed without merging**
