### PR TITLE
feat: Add HTTP2 for unencrypted HTTP

### PR DESCRIPTION
**Pull request by erezrokah**
Draft proposal for https://github.com/distribution/distribution/issues/4241 (currently intended for v2 releases).
Had to update some dependencies for this to work

You can test via:

```
docker build . -t registry:v2-h2c
docker run -p 5000:5000 registry:v2-h2c
```

Then on a separate shell:

```
curl -i --http2-prior-knowledge http://localhost:5000 
HTTP/2 200 
cache-control: no-cache
content-length: 0
date: Fri, 05 Jan 2024 15:40:04 GMT

curl -i http://localhost:5000
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Fri, 05 Jan 2024 15:40:31 GMT
Content-Length: 0
```

### CODE REVIEW

**Comment by erezrokah** [comment]
Help from the maintainers on the failing CI is appreciated

**Comment by milosgajdos** [comment]
Is there any reason why are you opening the PR from the `cloudquery` repo? 

Judging by the error message I smell some signing key issues -- though I presume this shouldn't matter I can't think of anything else other than some key shenanigans at the moment.

Any ideas @crazy-max ?

Also, weird that only 3 workflows have been triggered 🤨

**Comment by erezrokah** [comment]
> Is there any reason why are you opening the PR from the `cloudquery` repo?

No strong reason, I re-opened https://github.com/distribution/distribution/pull/4246 from my personal account and also added another commit to make this opt-in to avoid what could be a breaking chage

**Comment by erezrokah** [comment]
Closing in favor of https://github.com/distribution/distribution/pull/4246

**Pull request closed without merging**
