### PR TITLE
build(deps): bump docker/bake-action from 2 to 4

### PR DESCRIPTION
**Pull request by crazy-max**
carry and closes #4233 

This handles provenance for built artifacts and disable provenance when generating docs.

See https://github.com/distribution/distribution/actions/runs/7501643046/job/20422754661?pr=4253#step:9:40

### CODE REVIEW

**Review by milosgajdos — APPROVED** [review]
LGTM, but can u squash? PTAL @thaJeztah

**Comment by crazy-max** [comment]
> LGTM, but can u squash? PTAL @thaJeztah 

You mean squashing dependabot commit? I think we should keep it as this is just carried over.

**Comment by milosgajdos** [comment]
Nope, just your two commits into a single one

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
