### PR TITLE
Support all S3 instant retrieval storage classes

### LINKED ISSUE #3612: Support all S3 storage classes
Hi 👋 

It would be cool to be able to use different S3 storage classes for the backend.

Currently, setting `REGISTRY_STORAGE_S3_STORAGECLASS=INTELLIGENT_TIERING` results in:

```
panic: The storageclass parameter must be one of [NONE STANDARD REDUCED_REDUNDANCY], INTELLIGENT_TIERING invalid
```

From the [docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.put_object):
```
StorageClass='STANDARD'|'REDUCED_REDUNDANCY'|'STANDARD_IA'|'ONEZONE_IA'|'INTELLIGENT_TIERING'|'GLACIER'|'DEEP_ARCHIVE'|'OUTPOSTS'|'GLACIER_IR',
```

### PR DESCRIPTION
**Pull request by ddelange**
Closes #3612

Omits 'GLACIER'|'DEEP_ARCHIVE' storage classes, as they are not instant and therefore not suitable for the registry

### CODE REVIEW

**Comment by milosgajdos** [comment]
You need to sign your commit.

**Comment by ddelange** [comment]
@milosgajdos that's a nice check :) my git setup does it, but apparently GitHub UI doesn't 🤔

**Review by milosgajdos — COMMENTED** [review]
This looks ok. Can we add some tests here, please.

**Review by milosgajdos — APPROVED** [review]

**Comment by ddelange** [comment]
@milosgajdos are there more reviewers you could add?

**Comment by milosgajdos** [comment]
I've maxed out with the most active ones, but I'll ping @wy65701436

**Review by joaodrp — APPROVED** [review]
LGTM!

**Comment by ddelange** [comment]
@milosgajdos is this part of the 3.0.0 milestone ref https://github.com/distribution/distribution/issues/3721 ?

**Comment by milosgajdos** [comment]
it is now 😄

**Pull request merged**
