### PR TITLE
Add configuration parameter of expiring pull through cache

### PR DESCRIPTION
**Pull request by eastwd**
This PR is adding configuration parameter which change a pull through cache TTL for fixing this probrem.(#2367)

Signed-off-by: eastwd <bando142141@gmail.com>

### CODE REVIEW

**Comment by milosgajdos** [comment]
Thanks for the PR @eastwd. It seems like it might be a duplicate of https://github.com/distribution/distribution/pull/3238

**Comment by eastwd** [comment]
I see. I wait for the PR #3238 to be merged. Thanks.

**Comment by milosgajdos** [comment]
Would you mind closing this one in favor of #3238, then?

**Comment by messiahUA** [comment]
Do I understand correctly that this change has not been released yet?

**Comment by milosgajdos** [comment]
@messiahUA that's correct, yes. We have been trying to find some consensus in the other referenced PR, but it looks like it was a dead-end, so we might look into this as part of `v3` work.

**Pull request closed without merging**
