### PR TITLE
Incremental catalog iteration

### PR DESCRIPTION
**Pull request by sargun**
When dealing with lots of repositories it can be beneficial to have a
mechanism to iterate through the data in an interative or reentrant manner.
This introduces the idea of "offset", which says start iteration at a certain
point (offset, END] to enable this incremental listing behaviour.

This only implements this optimization for the S3 driver.

### CODE REVIEW

**Comment by sargun** [comment]
Bueler?

**Comment by deleteriousEffect** [comment]
@sargun could you please add a description for this MR? Especially since it appears like it might be in support of future work.

**Comment by sargun** [comment]
@deleteriousEffect Sorry, I thought that my commit comments had ended up in the description.

**Comment by milosgajdos** [comment]
Can you rebase @sargun? This should also trigger a new build -- the current one is "stale" because we changed GHA workflow names.

**Comment by sargun** [comment]
Sure.

**Comment by milosgajdos** [comment]
Just realized there is a PR that improves catalog I quickly picked up after the original author at some point, but never got it across the finish line due to being busy https://github.com/distribution/distribution/pull/3145 

NOTE: I havent looked into this PR, yet, only skimmed through it as it reminded me of #3145

**Comment by milosgajdos** [comment]
@sargun would you mind rebasing?

**Comment by Jamstah** [comment]
@sargun I think this is now covered by #3685. I'm afraid there were a bunch of walk related performance PRs and it got a bit messy.

Are you OK to close this one, or are there additional benefits we should rebase it for?

**Comment by milosgajdos** [comment]
ping @sargun re: https://github.com/distribution/distribution/pull/3360#issuecomment-1722461356

**Comment by milosgajdos** [comment]
Closing due to inactivity. Feel free to reopen if you believe #3685 is insufficient.

**Pull request closed without merging**
