### PR TITLE
typo: a client implementation

### PR DESCRIPTION
**Pull request by yecril71pl**

### CODE REVIEW

**Comment by milosgajdos** [comment]
Please sign your commit as per contribution guidelines.

**Comment by yecril71pl** [comment]
> Please sign your commit as per contribution guidelines.

I tried, is this what you want?

**Comment by milosgajdos** [comment]
Your **commit** is still not signed. Please follow this https://github.com/distribution/distribution/blob/main/CONTRIBUTING.md#sign-your-work

**Comment by yecril71pl** [comment]
Here is the exact instruction:
> Then you just add a line to every git commit message:
> Signed-off-by: Joe Smith <joe.smith@email.com>

There is 1 commit and the commit message contains the required line.  What is missing?

**Comment by milosgajdos** [comment]
If your read the [DCO output](https://github.com/distribution/distribution/pull/3435/checks?check_run_id=2851248928) from the GH action run you should see what the problem is.

**Comment by yecril71pl** [comment]
The DCO output *tells* me what the problem is but it does not let me *see* it.  I hope the instructions in there are better than in the documentation&mdash;the latter must be wrong since I following them did not help a single bit.

**Comment by yecril71pl** [comment]
> If your read the [DCO output](https://github.com/distribution/distribution/pull/3435/checks?check_run_id=2851248928) from the GH action run you should see what the problem is.

Thank you.  The problem was GitHub knows 2 my e-mail addresses for some reason (they are equivalent) but only one of them can be used for this purpose.

**Review by milosgajdos — APPROVED** [review]

**Review by joaodrp — APPROVED** [review]

**Pull request merged**
