### PR TITLE
Update Code of Conduct

### PR DESCRIPTION
**Pull request by milosgajdos**
Closes https://github.com/distribution/distribution/issues/3970

### CODE REVIEW

**Review by deleteriousEffect — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
- failure is unrelated; see https://github.com/distribution/distribution/issues/3972

**Comment by milosgajdos** [comment]
Once we merge https://github.com/distribution/distribution/pull/3973 I will rebase this PR and we should be good 😄

**Review by justincormack — APPROVED** [review]

**Comment by milosgajdos** [comment]
Ok, rebased to `main`, once the CI passes, I'll merge.

**Pull request merged**
